# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hour_Registry_PI_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PI_dialog(object):
    def setupUi(self, PI_dialog):
        PI_dialog.setObjectName("PI_dialog")
        PI_dialog.resize(606, 439)
        self.gridLayout_2 = QtWidgets.QGridLayout(PI_dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_project_info = QtWidgets.QFrame(PI_dialog)
        self.frame_project_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_project_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_project_info.setObjectName("frame_project_info")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_project_info)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_project_info = QtWidgets.QHBoxLayout()
        self.horizontalLayout_project_info.setObjectName("horizontalLayout_project_info")
        self.verticalLayout_project_info = QtWidgets.QVBoxLayout()
        self.verticalLayout_project_info.setObjectName("verticalLayout_project_info")
        self.horizontalLayout1_client = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_client.setObjectName("horizontalLayout1_client")
        self.label_client = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_client.sizePolicy().hasHeightForWidth())
        self.label_client.setSizePolicy(sizePolicy)
        self.label_client.setMinimumSize(QtCore.QSize(87, 0))
        self.label_client.setMaximumSize(QtCore.QSize(237, 35))
        self.label_client.setStyleSheet("QLabel{\n"
"    max-width: 215px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_client.setScaledContents(False)
        self.label_client.setAlignment(QtCore.Qt.AlignCenter)
        self.label_client.setWordWrap(False)
        self.label_client.setObjectName("label_client")
        self.horizontalLayout1_client.addWidget(self.label_client)
        self.lineEdit_client = QtWidgets.QLineEdit(self.frame_project_info)
        self.lineEdit_client.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_client.sizePolicy().hasHeightForWidth())
        self.lineEdit_client.setSizePolicy(sizePolicy)
        self.lineEdit_client.setMinimumSize(QtCore.QSize(101, 0))
        self.lineEdit_client.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_client.setObjectName("lineEdit_client")
        self.horizontalLayout1_client.addWidget(self.lineEdit_client)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout1_client)
        self.horizontalLayout_p_name = QtWidgets.QHBoxLayout()
        self.horizontalLayout_p_name.setObjectName("horizontalLayout_p_name")
        self.label_p_name = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_p_name.sizePolicy().hasHeightForWidth())
        self.label_p_name.setSizePolicy(sizePolicy)
        self.label_p_name.setMinimumSize(QtCore.QSize(87, 0))
        self.label_p_name.setMaximumSize(QtCore.QSize(237, 35))
        self.label_p_name.setStyleSheet("QLabel{\n"
"    max-width: 215px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_p_name.setScaledContents(False)
        self.label_p_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_p_name.setWordWrap(False)
        self.label_p_name.setObjectName("label_p_name")
        self.horizontalLayout_p_name.addWidget(self.label_p_name)
        self.lineEdit_p_name = QtWidgets.QLineEdit(self.frame_project_info)
        self.lineEdit_p_name.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_p_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_p_name.setSizePolicy(sizePolicy)
        self.lineEdit_p_name.setMinimumSize(QtCore.QSize(101, 0))
        self.lineEdit_p_name.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_p_name.setObjectName("lineEdit_p_name")
        self.horizontalLayout_p_name.addWidget(self.lineEdit_p_name)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_p_name)
        self.horizontalLayout_p_number = QtWidgets.QHBoxLayout()
        self.horizontalLayout_p_number.setObjectName("horizontalLayout_p_number")
        self.label_p_number = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_p_number.sizePolicy().hasHeightForWidth())
        self.label_p_number.setSizePolicy(sizePolicy)
        self.label_p_number.setMinimumSize(QtCore.QSize(87, 0))
        self.label_p_number.setMaximumSize(QtCore.QSize(237, 35))
        self.label_p_number.setStyleSheet("QLabel{\n"
"    max-width: 215px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_p_number.setScaledContents(False)
        self.label_p_number.setAlignment(QtCore.Qt.AlignCenter)
        self.label_p_number.setWordWrap(False)
        self.label_p_number.setObjectName("label_p_number")
        self.horizontalLayout_p_number.addWidget(self.label_p_number)
        self.lineEdit_p_number = QtWidgets.QLineEdit(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_p_number.sizePolicy().hasHeightForWidth())
        self.lineEdit_p_number.setSizePolicy(sizePolicy)
        self.lineEdit_p_number.setMinimumSize(QtCore.QSize(101, 0))
        self.lineEdit_p_number.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_p_number.setObjectName("lineEdit_p_number")
        self.horizontalLayout_p_number.addWidget(self.lineEdit_p_number)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_p_number)
        self.horizontalLayout_t_number = QtWidgets.QHBoxLayout()
        self.horizontalLayout_t_number.setObjectName("horizontalLayout_t_number")
        self.label_t_number = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_t_number.sizePolicy().hasHeightForWidth())
        self.label_t_number.setSizePolicy(sizePolicy)
        self.label_t_number.setMinimumSize(QtCore.QSize(87, 0))
        self.label_t_number.setMaximumSize(QtCore.QSize(237, 35))
        self.label_t_number.setStyleSheet("QLabel{\n"
"    max-width: 215px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_t_number.setScaledContents(False)
        self.label_t_number.setAlignment(QtCore.Qt.AlignCenter)
        self.label_t_number.setWordWrap(False)
        self.label_t_number.setObjectName("label_t_number")
        self.horizontalLayout_t_number.addWidget(self.label_t_number)
        self.lineEdit_t_number = QtWidgets.QLineEdit(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_t_number.sizePolicy().hasHeightForWidth())
        self.lineEdit_t_number.setSizePolicy(sizePolicy)
        self.lineEdit_t_number.setMinimumSize(QtCore.QSize(101, 0))
        self.lineEdit_t_number.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_t_number.setObjectName("lineEdit_t_number")
        self.horizontalLayout_t_number.addWidget(self.lineEdit_t_number)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_t_number)
        self.horizontalLayout_currency = QtWidgets.QHBoxLayout()
        self.horizontalLayout_currency.setObjectName("horizontalLayout_currency")
        self.checkBox_billable = QtWidgets.QCheckBox(self.frame_project_info)
        self.checkBox_billable.setStyleSheet("QCheckBox{\n"
"    max-width: 100px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"}\n"
"QCheckBox::indicator{\n"
"margin-left:5%; margin-right:5%;\n"
"width: 30px;\n"
"height: 30px;\n"
"}\n"
"\n"
"QCheckBox::indicator::unchecked{\n"
"    image: url(:/images/icons8-toggle-off-100.png);\n"
"\n"
"}\n"
"\n"
"QCheckBox::indicator::checked{\n"
"    image: url(:/images/icons8-toggle-on-100.png);\n"
"}\n"
"")
        self.checkBox_billable.setChecked(True)
        self.checkBox_billable.setObjectName("checkBox_billable")
        self.horizontalLayout_currency.addWidget(self.checkBox_billable)
        self.label_rate = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_rate.sizePolicy().hasHeightForWidth())
        self.label_rate.setSizePolicy(sizePolicy)
        self.label_rate.setMinimumSize(QtCore.QSize(87, 0))
        self.label_rate.setMaximumSize(QtCore.QSize(122, 35))
        self.label_rate.setStyleSheet("QLabel{\n"
"    max-width: 100px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_rate.setScaledContents(False)
        self.label_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rate.setWordWrap(False)
        self.label_rate.setObjectName("label_rate")
        self.horizontalLayout_currency.addWidget(self.label_rate)
        self.lineEdit_rate = QtWidgets.QLineEdit(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rate.sizePolicy().hasHeightForWidth())
        self.lineEdit_rate.setSizePolicy(sizePolicy)
        self.lineEdit_rate.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_rate.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_rate.setObjectName("lineEdit_rate")
        self.horizontalLayout_currency.addWidget(self.lineEdit_rate)
        self.comboBox_currency = QtWidgets.QComboBox(self.frame_project_info)
        self.comboBox_currency.setMaximumSize(QtCore.QSize(122, 35))
        self.comboBox_currency.setStyleSheet("QComboBox{\n"
"    max-width: 100px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QComboBox::hover{\n"
"    background-color: rgb(182, 182, 182) ;\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.comboBox_currency.setObjectName("comboBox_currency")
        self.comboBox_currency.addItem("")
        self.comboBox_currency.addItem("")
        self.horizontalLayout_currency.addWidget(self.comboBox_currency)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_currency)
        self.horizontalLayout_p_manager = QtWidgets.QHBoxLayout()
        self.horizontalLayout_p_manager.setObjectName("horizontalLayout_p_manager")
        self.label_p_manager = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_p_manager.sizePolicy().hasHeightForWidth())
        self.label_p_manager.setSizePolicy(sizePolicy)
        self.label_p_manager.setMinimumSize(QtCore.QSize(87, 0))
        self.label_p_manager.setMaximumSize(QtCore.QSize(237, 35))
        self.label_p_manager.setStyleSheet("QLabel{\n"
"    max-width: 215px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_p_manager.setScaledContents(False)
        self.label_p_manager.setAlignment(QtCore.Qt.AlignCenter)
        self.label_p_manager.setWordWrap(False)
        self.label_p_manager.setObjectName("label_p_manager")
        self.horizontalLayout_p_manager.addWidget(self.label_p_manager)
        self.lineEdit_p_manager = QtWidgets.QLineEdit(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_p_manager.sizePolicy().hasHeightForWidth())
        self.lineEdit_p_manager.setSizePolicy(sizePolicy)
        self.lineEdit_p_manager.setMinimumSize(QtCore.QSize(101, 0))
        self.lineEdit_p_manager.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_p_manager.setObjectName("lineEdit_p_manager")
        self.horizontalLayout_p_manager.addWidget(self.lineEdit_p_manager)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_p_manager)
        self.horizontalLayout1_client_contact = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_client_contact.setObjectName("horizontalLayout1_client_contact")
        self.label_client_contact = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_client_contact.sizePolicy().hasHeightForWidth())
        self.label_client_contact.setSizePolicy(sizePolicy)
        self.label_client_contact.setMinimumSize(QtCore.QSize(87, 0))
        self.label_client_contact.setMaximumSize(QtCore.QSize(237, 35))
        self.label_client_contact.setStyleSheet("QLabel{\n"
"    max-width: 215px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_client_contact.setScaledContents(False)
        self.label_client_contact.setAlignment(QtCore.Qt.AlignCenter)
        self.label_client_contact.setWordWrap(False)
        self.label_client_contact.setObjectName("label_client_contact")
        self.horizontalLayout1_client_contact.addWidget(self.label_client_contact)
        self.lineEdit_client_contact = QtWidgets.QLineEdit(self.frame_project_info)
        self.lineEdit_client_contact.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_client_contact.sizePolicy().hasHeightForWidth())
        self.lineEdit_client_contact.setSizePolicy(sizePolicy)
        self.lineEdit_client_contact.setMinimumSize(QtCore.QSize(101, 0))
        self.lineEdit_client_contact.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_client_contact.setObjectName("lineEdit_client_contact")
        self.horizontalLayout1_client_contact.addWidget(self.lineEdit_client_contact)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout1_client_contact)
        self.horizontalLayout_add_info = QtWidgets.QHBoxLayout()
        self.horizontalLayout_add_info.setObjectName("horizontalLayout_add_info")
        self.label_add_info = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_add_info.sizePolicy().hasHeightForWidth())
        self.label_add_info.setSizePolicy(sizePolicy)
        self.label_add_info.setMinimumSize(QtCore.QSize(87, 0))
        self.label_add_info.setMaximumSize(QtCore.QSize(237, 35))
        self.label_add_info.setStyleSheet("QLabel{\n"
"    max-width: 215px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_add_info.setScaledContents(False)
        self.label_add_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_add_info.setWordWrap(False)
        self.label_add_info.setObjectName("label_add_info")
        self.horizontalLayout_add_info.addWidget(self.label_add_info)
        self.lineEdit_add_info = QtWidgets.QLineEdit(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_add_info.sizePolicy().hasHeightForWidth())
        self.lineEdit_add_info.setSizePolicy(sizePolicy)
        self.lineEdit_add_info.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_add_info.setObjectName("lineEdit_add_info")
        self.horizontalLayout_add_info.addWidget(self.lineEdit_add_info)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_add_info)
        self.horizontalLayout_project_info.addLayout(self.verticalLayout_project_info)
        self.verticalLayout.addLayout(self.horizontalLayout_project_info)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_edit = QtWidgets.QPushButton(self.frame_project_info)
        self.pushButton_edit.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(206, 232, 255) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 144, 144);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_edit.setObjectName("pushButton_edit")
        self.horizontalLayout.addWidget(self.pushButton_edit)
        self.pushButton_cancel = QtWidgets.QPushButton(self.frame_project_info)
        self.pushButton_cancel.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(206, 232, 255) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 144, 144);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_project_info, 0, 0, 1, 1)

        self.retranslateUi(PI_dialog)
        self.checkBox_billable.stateChanged['int'].connect(PI_dialog.billable_changed)
        self.pushButton_edit.clicked.connect(PI_dialog.edit_project)
        self.pushButton_cancel.clicked.connect(PI_dialog.close)
        QtCore.QMetaObject.connectSlotsByName(PI_dialog)

    def retranslateUi(self, PI_dialog):
        _translate = QtCore.QCoreApplication.translate
        PI_dialog.setWindowTitle(_translate("PI_dialog", "Dialog"))
        self.label_client.setText(_translate("PI_dialog", "Client"))
        self.label_p_name.setText(_translate("PI_dialog", "Project Name"))
        self.label_p_number.setText(_translate("PI_dialog", "Project Number"))
        self.label_t_number.setText(_translate("PI_dialog", "Task Number"))
        self.checkBox_billable.setText(_translate("PI_dialog", "Billable"))
        self.label_rate.setText(_translate("PI_dialog", "Hourly Rate"))
        self.comboBox_currency.setItemText(0, _translate("PI_dialog", "€ Euro"))
        self.comboBox_currency.setItemText(1, _translate("PI_dialog", "$ Dollar"))
        self.label_p_manager.setText(_translate("PI_dialog", "Project Manager"))
        self.label_client_contact.setText(_translate("PI_dialog", "Client Contact"))
        self.label_add_info.setText(_translate("PI_dialog", "Additional Information"))
        self.pushButton_edit.setText(_translate("PI_dialog", "Edit"))
        self.pushButton_cancel.setText(_translate("PI_dialog", "Cancel"))
import resource_file_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PI_dialog = QtWidgets.QDialog()
    ui = Ui_PI_dialog()
    ui.setupUi(PI_dialog)
    PI_dialog.show()
    sys.exit(app.exec_())
