# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hour_Registry_DH_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DH_dialog(object):
    def setupUi(self, DH_dialog):
        DH_dialog.setObjectName("DH_dialog")
        DH_dialog.resize(449, 375)
        self.gridLayout = QtWidgets.QGridLayout(DH_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_date = QtWidgets.QHBoxLayout()
        self.horizontalLayout_date.setObjectName("horizontalLayout_date")
        self.pushButton_date = QtWidgets.QPushButton(DH_dialog)
        self.pushButton_date.setStyleSheet("QPushButton{\n"
"    max-width: 215px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    max-width: 215px;\n"
"    background-color: rgb(174, 174, 174);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_date.setObjectName("pushButton_date")
        self.horizontalLayout_date.addWidget(self.pushButton_date)
        self.dateEdit = QtWidgets.QDateEdit(DH_dialog)
        self.dateEdit.setMinimumSize(QtCore.QSize(130, 0))
        self.dateEdit.setStyleSheet("QDateEdit{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 4px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: 14px;\n"
"\n"
"    padding: 6px;\n"
"}\n"
"\n"
"\n"
"")
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_date.addWidget(self.dateEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_date)
        self.horizontalLayout_start = QtWidgets.QHBoxLayout()
        self.horizontalLayout_start.setObjectName("horizontalLayout_start")
        self.pushButton_start = QtWidgets.QPushButton(DH_dialog)
        self.pushButton_start.setMinimumSize(QtCore.QSize(87, 0))
        self.pushButton_start.setStyleSheet("QPushButton{\n"
"    max-width: 215px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    max-width: 215px;\n"
"    background-color: rgb(174, 174, 174);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_start.addWidget(self.pushButton_start)
        self.timeEdit_start = QtWidgets.QTimeEdit(DH_dialog)
        self.timeEdit_start.setStyleSheet("QTimeEdit{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"\n"
"    border-width: 4px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: 14px;\n"
"\n"
"    padding: 6px;\n"
"}")
        self.timeEdit_start.setCalendarPopup(False)
        self.timeEdit_start.setObjectName("timeEdit_start")
        self.horizontalLayout_start.addWidget(self.timeEdit_start)
        self.verticalLayout.addLayout(self.horizontalLayout_start)
        self.horizontalLayout_end = QtWidgets.QHBoxLayout()
        self.horizontalLayout_end.setObjectName("horizontalLayout_end")
        self.pushButton_end = QtWidgets.QPushButton(DH_dialog)
        self.pushButton_end.setMinimumSize(QtCore.QSize(87, 0))
        self.pushButton_end.setStyleSheet("QPushButton{\n"
"    max-width: 215px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    max-width: 215px;\n"
"    background-color: rgb(174, 174, 174);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_end.setObjectName("pushButton_end")
        self.horizontalLayout_end.addWidget(self.pushButton_end)
        self.timeEdit_end = QtWidgets.QTimeEdit(DH_dialog)
        self.timeEdit_end.setStyleSheet("QTimeEdit{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"\n"
"    border-width: 4px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: 14px;\n"
"\n"
"    padding: 6px;\n"
"}")
        self.timeEdit_end.setObjectName("timeEdit_end")
        self.horizontalLayout_end.addWidget(self.timeEdit_end)
        self.verticalLayout.addLayout(self.horizontalLayout_end)
        self.horizontalLayout_duration = QtWidgets.QHBoxLayout()
        self.horizontalLayout_duration.setObjectName("horizontalLayout_duration")
        self.label_duration = QtWidgets.QLabel(DH_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_duration.sizePolicy().hasHeightForWidth())
        self.label_duration.setSizePolicy(sizePolicy)
        self.label_duration.setMinimumSize(QtCore.QSize(87, 0))
        self.label_duration.setMaximumSize(QtCore.QSize(237, 35))
        self.label_duration.setStyleSheet("QLabel{\n"
"    max-width: 215px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_duration.setScaledContents(False)
        self.label_duration.setAlignment(QtCore.Qt.AlignCenter)
        self.label_duration.setWordWrap(False)
        self.label_duration.setObjectName("label_duration")
        self.horizontalLayout_duration.addWidget(self.label_duration)
        self.label_duration_time = QtWidgets.QLabel(DH_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_duration_time.sizePolicy().hasHeightForWidth())
        self.label_duration_time.setSizePolicy(sizePolicy)
        self.label_duration_time.setMinimumSize(QtCore.QSize(0, 0))
        self.label_duration_time.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_duration_time.setStyleSheet("QLabel{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.label_duration_time.setText("")
        self.label_duration_time.setScaledContents(False)
        self.label_duration_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_duration_time.setWordWrap(False)
        self.label_duration_time.setObjectName("label_duration_time")
        self.horizontalLayout_duration.addWidget(self.label_duration_time)
        self.verticalLayout.addLayout(self.horizontalLayout_duration)
        self.horizontalLayout_project = QtWidgets.QHBoxLayout()
        self.horizontalLayout_project.setObjectName("horizontalLayout_project")
        self.label_project = QtWidgets.QLabel(DH_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_project.sizePolicy().hasHeightForWidth())
        self.label_project.setSizePolicy(sizePolicy)
        self.label_project.setMinimumSize(QtCore.QSize(87, 0))
        self.label_project.setMaximumSize(QtCore.QSize(237, 35))
        self.label_project.setStyleSheet("QLabel{\n"
"    max-width: 215px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_project.setScaledContents(False)
        self.label_project.setAlignment(QtCore.Qt.AlignCenter)
        self.label_project.setWordWrap(False)
        self.label_project.setObjectName("label_project")
        self.horizontalLayout_project.addWidget(self.label_project)
        self.comboBox_project_add = QtWidgets.QComboBox(DH_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_project_add.sizePolicy().hasHeightForWidth())
        self.comboBox_project_add.setSizePolicy(sizePolicy)
        self.comboBox_project_add.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_project_add.setStyleSheet("QComboBox{\n"
"    background-color: rgb(245, 245, 220);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}\n"
"QComboBox::hover{\n"
"    background-color:rgb(234, 234, 210) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.comboBox_project_add.setObjectName("comboBox_project_add")
        self.horizontalLayout_project.addWidget(self.comboBox_project_add)
        self.verticalLayout.addLayout(self.horizontalLayout_project)
        self.horizontalLayout_add_info = QtWidgets.QHBoxLayout()
        self.horizontalLayout_add_info.setObjectName("horizontalLayout_add_info")
        self.label_add_info = QtWidgets.QLabel(DH_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_add_info.sizePolicy().hasHeightForWidth())
        self.label_add_info.setSizePolicy(sizePolicy)
        self.label_add_info.setMinimumSize(QtCore.QSize(87, 0))
        self.label_add_info.setMaximumSize(QtCore.QSize(237, 35))
        self.label_add_info.setStyleSheet("QLabel{\n"
"    max-width: 215px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_add_info.setScaledContents(False)
        self.label_add_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_add_info.setWordWrap(False)
        self.label_add_info.setObjectName("label_add_info")
        self.horizontalLayout_add_info.addWidget(self.label_add_info)
        self.lineEdit_add_info = QtWidgets.QLineEdit(DH_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_add_info.sizePolicy().hasHeightForWidth())
        self.lineEdit_add_info.setSizePolicy(sizePolicy)
        self.lineEdit_add_info.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_add_info.setStyleSheet("QLineEdit{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_add_info.setObjectName("lineEdit_add_info")
        self.horizontalLayout_add_info.addWidget(self.lineEdit_add_info)
        self.verticalLayout.addLayout(self.horizontalLayout_add_info)
        self.horizontalLayout_edit = QtWidgets.QHBoxLayout()
        self.horizontalLayout_edit.setObjectName("horizontalLayout_edit")
        self.pushButton_edit_table = QtWidgets.QPushButton(DH_dialog)
        self.pushButton_edit_table.setMinimumSize(QtCore.QSize(192, 0))
        self.pushButton_edit_table.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(206, 232, 255) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color:rgb(255, 144, 144);\n"
"\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_edit_table.setObjectName("pushButton_edit_table")
        self.horizontalLayout_edit.addWidget(self.pushButton_edit_table)
        self.pushButton_cancel = QtWidgets.QPushButton(DH_dialog)
        self.pushButton_cancel.setMinimumSize(QtCore.QSize(192, 0))
        self.pushButton_cancel.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(206, 232, 255) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color:rgb(255, 144, 144);\n"
"\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_edit.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_edit)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(DH_dialog)
        self.pushButton_date.clicked.connect(DH_dialog.date_now)
        self.pushButton_end.clicked.connect(DH_dialog.end_now)
        self.pushButton_start.clicked.connect(DH_dialog.start_now)
        self.pushButton_cancel.clicked.connect(DH_dialog.close)
        self.pushButton_edit_table.clicked.connect(DH_dialog.edit_daily)
        QtCore.QMetaObject.connectSlotsByName(DH_dialog)

    def retranslateUi(self, DH_dialog):
        _translate = QtCore.QCoreApplication.translate
        DH_dialog.setWindowTitle(_translate("DH_dialog", "Dialog"))
        self.pushButton_date.setText(_translate("DH_dialog", "Date"))
        self.pushButton_start.setText(_translate("DH_dialog", "Start "))
        self.pushButton_end.setText(_translate("DH_dialog", "End"))
        self.label_duration.setText(_translate("DH_dialog", "Duration"))
        self.label_project.setText(_translate("DH_dialog", "Project"))
        self.label_add_info.setText(_translate("DH_dialog", "Additional information"))
        self.pushButton_edit_table.setText(_translate("DH_dialog", "Edit Table"))
        self.pushButton_cancel.setText(_translate("DH_dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DH_dialog = QtWidgets.QDialog()
    ui = Ui_DH_dialog()
    ui.setupUi(DH_dialog)
    DH_dialog.show()
    sys.exit(app.exec_())
