# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hour_Registry_PI_dialog_QT.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjectInput_edit_dialog(object):
    def setupUi(self, ProjectInput_edit_dialog):
        ProjectInput_edit_dialog.setObjectName("ProjectInput_edit_dialog")
        ProjectInput_edit_dialog.resize(517, 386)
        self.gridLayout_2 = QtWidgets.QGridLayout(ProjectInput_edit_dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_project_info = QtWidgets.QFrame(ProjectInput_edit_dialog)
        self.frame_project_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_project_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_project_info.setObjectName("frame_project_info")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_project_info)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_project_info = QtWidgets.QHBoxLayout()
        self.horizontalLayout_project_info.setObjectName("horizontalLayout_project_info")
        self.verticalLayout_project_info = QtWidgets.QVBoxLayout()
        self.verticalLayout_project_info.setObjectName("verticalLayout_project_info")
        self.horizontalLayout1_client = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_client.setObjectName("horizontalLayout1_client")
        self.label_client = QtWidgets.QLabel(self.frame_project_info)
        self.label_client.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_client.sizePolicy().hasHeightForWidth())
        self.label_client.setSizePolicy(sizePolicy)
        self.label_client.setMinimumSize(QtCore.QSize(0, 0))
        self.label_client.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_client.setStyleSheet("QLabel{\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.label_client.setScaledContents(False)
        self.label_client.setAlignment(QtCore.Qt.AlignCenter)
        self.label_client.setWordWrap(False)
        self.label_client.setObjectName("label_client")
        self.horizontalLayout1_client.addWidget(self.label_client)
        self.lineEdit_client = QtWidgets.QLineEdit(self.frame_project_info)
        self.lineEdit_client.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_client.sizePolicy().hasHeightForWidth())
        self.lineEdit_client.setSizePolicy(sizePolicy)
        self.lineEdit_client.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_client.setStyleSheet("QLineEdit{\n"
"    background-color:beige;    \n"
"    border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_client.setObjectName("lineEdit_client")
        self.horizontalLayout1_client.addWidget(self.lineEdit_client)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout1_client)
        self.horizontalLayout_project_name = QtWidgets.QHBoxLayout()
        self.horizontalLayout_project_name.setObjectName("horizontalLayout_project_name")
        self.label_project_name = QtWidgets.QLabel(self.frame_project_info)
        self.label_project_name.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_project_name.sizePolicy().hasHeightForWidth())
        self.label_project_name.setSizePolicy(sizePolicy)
        self.label_project_name.setMinimumSize(QtCore.QSize(0, 0))
        self.label_project_name.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_project_name.setStyleSheet("QLabel{\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.label_project_name.setScaledContents(False)
        self.label_project_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_project_name.setWordWrap(False)
        self.label_project_name.setObjectName("label_project_name")
        self.horizontalLayout_project_name.addWidget(self.label_project_name)
        self.lineEdit_project_name = QtWidgets.QLineEdit(self.frame_project_info)
        self.lineEdit_project_name.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_project_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_project_name.setSizePolicy(sizePolicy)
        self.lineEdit_project_name.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_project_name.setStyleSheet("QLineEdit{\n"
"    background-color:beige;    \n"
"    border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_project_name.setObjectName("lineEdit_project_name")
        self.horizontalLayout_project_name.addWidget(self.lineEdit_project_name)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_project_name)
        self.horizontalLayout_project_number = QtWidgets.QHBoxLayout()
        self.horizontalLayout_project_number.setObjectName("horizontalLayout_project_number")
        self.label_project_number = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_project_number.sizePolicy().hasHeightForWidth())
        self.label_project_number.setSizePolicy(sizePolicy)
        self.label_project_number.setMinimumSize(QtCore.QSize(0, 0))
        self.label_project_number.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_project_number.setStyleSheet("QLabel{\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.label_project_number.setScaledContents(False)
        self.label_project_number.setAlignment(QtCore.Qt.AlignCenter)
        self.label_project_number.setWordWrap(False)
        self.label_project_number.setObjectName("label_project_number")
        self.horizontalLayout_project_number.addWidget(self.label_project_number)
        self.lineEdit_project_number = QtWidgets.QLineEdit(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_project_number.sizePolicy().hasHeightForWidth())
        self.lineEdit_project_number.setSizePolicy(sizePolicy)
        self.lineEdit_project_number.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_project_number.setStyleSheet("QLineEdit{\n"
"    background-color:beige;    \n"
"    border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_project_number.setObjectName("lineEdit_project_number")
        self.horizontalLayout_project_number.addWidget(self.lineEdit_project_number)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_project_number)
        self.horizontalLayout_Oracle_name = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Oracle_name.setObjectName("horizontalLayout_Oracle_name")
        self.label_Oracle_name = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Oracle_name.sizePolicy().hasHeightForWidth())
        self.label_Oracle_name.setSizePolicy(sizePolicy)
        self.label_Oracle_name.setMinimumSize(QtCore.QSize(0, 0))
        self.label_Oracle_name.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_Oracle_name.setStyleSheet("QLabel{\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.label_Oracle_name.setScaledContents(False)
        self.label_Oracle_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Oracle_name.setWordWrap(False)
        self.label_Oracle_name.setObjectName("label_Oracle_name")
        self.horizontalLayout_Oracle_name.addWidget(self.label_Oracle_name)
        self.lineEdit_Oracle_name = QtWidgets.QLineEdit(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Oracle_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_Oracle_name.setSizePolicy(sizePolicy)
        self.lineEdit_Oracle_name.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_Oracle_name.setStyleSheet("QLineEdit{\n"
"    background-color:beige;    \n"
"    border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_Oracle_name.setObjectName("lineEdit_Oracle_name")
        self.horizontalLayout_Oracle_name.addWidget(self.lineEdit_Oracle_name)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_Oracle_name)
        self.horizontalLayout_project_manager = QtWidgets.QHBoxLayout()
        self.horizontalLayout_project_manager.setObjectName("horizontalLayout_project_manager")
        self.label_project_manager = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_project_manager.sizePolicy().hasHeightForWidth())
        self.label_project_manager.setSizePolicy(sizePolicy)
        self.label_project_manager.setMinimumSize(QtCore.QSize(0, 0))
        self.label_project_manager.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_project_manager.setStyleSheet("QLabel{\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.label_project_manager.setScaledContents(False)
        self.label_project_manager.setAlignment(QtCore.Qt.AlignCenter)
        self.label_project_manager.setWordWrap(False)
        self.label_project_manager.setObjectName("label_project_manager")
        self.horizontalLayout_project_manager.addWidget(self.label_project_manager)
        self.lineEdit_project_manager = QtWidgets.QLineEdit(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_project_manager.sizePolicy().hasHeightForWidth())
        self.lineEdit_project_manager.setSizePolicy(sizePolicy)
        self.lineEdit_project_manager.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_project_manager.setStyleSheet("QLineEdit{\n"
"    background-color:beige;    \n"
"    border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_project_manager.setObjectName("lineEdit_project_manager")
        self.horizontalLayout_project_manager.addWidget(self.lineEdit_project_manager)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_project_manager)
        self.horizontalLayout_client_contact = QtWidgets.QHBoxLayout()
        self.horizontalLayout_client_contact.setObjectName("horizontalLayout_client_contact")
        self.label_client_contact = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_client_contact.sizePolicy().hasHeightForWidth())
        self.label_client_contact.setSizePolicy(sizePolicy)
        self.label_client_contact.setMinimumSize(QtCore.QSize(0, 0))
        self.label_client_contact.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_client_contact.setStyleSheet("QLabel{\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.label_client_contact.setScaledContents(False)
        self.label_client_contact.setAlignment(QtCore.Qt.AlignCenter)
        self.label_client_contact.setWordWrap(False)
        self.label_client_contact.setObjectName("label_client_contact")
        self.horizontalLayout_client_contact.addWidget(self.label_client_contact)
        self.lineEdit_client_contact = QtWidgets.QLineEdit(self.frame_project_info)
        self.lineEdit_client_contact.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_client_contact.sizePolicy().hasHeightForWidth())
        self.lineEdit_client_contact.setSizePolicy(sizePolicy)
        self.lineEdit_client_contact.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_client_contact.setStyleSheet("QLineEdit{\n"
"    background-color:beige;    \n"
"    border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_client_contact.setObjectName("lineEdit_client_contact")
        self.horizontalLayout_client_contact.addWidget(self.lineEdit_client_contact)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_client_contact)
        self.horizontalLayout_additional_information = QtWidgets.QHBoxLayout()
        self.horizontalLayout_additional_information.setObjectName("horizontalLayout_additional_information")
        self.label_additional_information = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_additional_information.sizePolicy().hasHeightForWidth())
        self.label_additional_information.setSizePolicy(sizePolicy)
        self.label_additional_information.setMinimumSize(QtCore.QSize(0, 0))
        self.label_additional_information.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_additional_information.setStyleSheet("QLabel{\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.label_additional_information.setScaledContents(False)
        self.label_additional_information.setAlignment(QtCore.Qt.AlignCenter)
        self.label_additional_information.setWordWrap(False)
        self.label_additional_information.setObjectName("label_additional_information")
        self.horizontalLayout_additional_information.addWidget(self.label_additional_information)
        self.lineEdit_additional_information = QtWidgets.QLineEdit(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_additional_information.sizePolicy().hasHeightForWidth())
        self.lineEdit_additional_information.setSizePolicy(sizePolicy)
        self.lineEdit_additional_information.setStyleSheet("QLineEdit{\n"
"    background-color:beige;    \n"
"    border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_additional_information.setObjectName("lineEdit_additional_information")
        self.horizontalLayout_additional_information.addWidget(self.lineEdit_additional_information)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_additional_information)
        self.horizontalLayout_project_info.addLayout(self.verticalLayout_project_info)
        self.verticalLayout.addLayout(self.horizontalLayout_project_info)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_edit = QtWidgets.QPushButton(self.frame_project_info)
        self.pushButton_edit.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(206, 232, 255) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 144, 144);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_edit.setObjectName("pushButton_edit")
        self.horizontalLayout.addWidget(self.pushButton_edit)
        self.pushButton_cancel = QtWidgets.QPushButton(self.frame_project_info)
        self.pushButton_cancel.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(206, 232, 255) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 144, 144);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_project_info, 0, 0, 1, 1)

        self.retranslateUi(ProjectInput_edit_dialog)
        self.pushButton_edit.clicked.connect(ProjectInput_edit_dialog.edit_project) # type: ignore
        self.pushButton_cancel.clicked.connect(ProjectInput_edit_dialog.close) # type: ignore
        self.lineEdit_project_number.textChanged['QString'].connect(ProjectInput_edit_dialog.name_number_changed) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ProjectInput_edit_dialog)

    def retranslateUi(self, ProjectInput_edit_dialog):
        _translate = QtCore.QCoreApplication.translate
        ProjectInput_edit_dialog.setWindowTitle(_translate("ProjectInput_edit_dialog", "Dialog"))
        self.label_client.setText(_translate("ProjectInput_edit_dialog", "Client"))
        self.label_project_name.setText(_translate("ProjectInput_edit_dialog", "Project Name"))
        self.lineEdit_project_name.setToolTip(_translate("ProjectInput_edit_dialog", "The Project Name cannot be changed due to its relation  \n"
" with Task Names and Daily Hours."))
        self.label_project_number.setText(_translate("ProjectInput_edit_dialog", "Project Number"))
        self.label_Oracle_name.setText(_translate("ProjectInput_edit_dialog", "Oracle Name"))
        self.label_project_manager.setText(_translate("ProjectInput_edit_dialog", "Project Manager"))
        self.label_client_contact.setText(_translate("ProjectInput_edit_dialog", "Client Contact"))
        self.label_additional_information.setText(_translate("ProjectInput_edit_dialog", "Additional Information"))
        self.pushButton_edit.setText(_translate("ProjectInput_edit_dialog", "Edit"))
        self.pushButton_cancel.setText(_translate("ProjectInput_edit_dialog", "Cancel"))
import resource_file_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProjectInput_edit_dialog = QtWidgets.QDialog()
    ui = Ui_ProjectInput_edit_dialog()
    ui.setupUi(ProjectInput_edit_dialog)
    ProjectInput_edit_dialog.show()
    sys.exit(app.exec_())
