# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hour_Registry_PI_dialog_QT.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_ProjectInput_edit_dialog(object):
    def setupUi(self, ProjectInput_edit_dialog):
        ProjectInput_edit_dialog.setObjectName("ProjectInput_edit_dialog")
        ProjectInput_edit_dialog.resize(606, 439)
        self.gridLayout_2 = QtWidgets.QGridLayout(ProjectInput_edit_dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_project_info = QtWidgets.QFrame(ProjectInput_edit_dialog)
        self.frame_project_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_project_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_project_info.setObjectName("frame_project_info")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_project_info)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_project_info = QtWidgets.QHBoxLayout()
        self.horizontalLayout_project_info.setObjectName("horizontalLayout_project_info")
        self.verticalLayout_project_info = QtWidgets.QVBoxLayout()
        self.verticalLayout_project_info.setObjectName("verticalLayout_project_info")
        self.horizontalLayout1_client = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_client.setObjectName("horizontalLayout1_client")
        self.label_client = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_client.sizePolicy().hasHeightForWidth())
        self.label_client.setSizePolicy(sizePolicy)
        self.label_client.setMinimumSize(QtCore.QSize(87, 0))
        self.label_client.setMaximumSize(QtCore.QSize(237, 35))
        self.label_client.setStyleSheet("QLabel{\n"
"    max-width: 215px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_client.setScaledContents(False)
        self.label_client.setAlignment(QtCore.Qt.AlignCenter)
        self.label_client.setWordWrap(False)
        self.label_client.setObjectName("label_client")
        self.horizontalLayout1_client.addWidget(self.label_client)
        self.lineEdit_client = QtWidgets.QLineEdit(self.frame_project_info)
        self.lineEdit_client.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_client.sizePolicy().hasHeightForWidth())
        self.lineEdit_client.setSizePolicy(sizePolicy)
        self.lineEdit_client.setMinimumSize(QtCore.QSize(101, 0))
        self.lineEdit_client.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_client.setObjectName("lineEdit_client")
        self.horizontalLayout1_client.addWidget(self.lineEdit_client)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout1_client)
        self.horizontalLayout_project_name = QtWidgets.QHBoxLayout()
        self.horizontalLayout_project_name.setObjectName("horizontalLayout_project_name")
        self.label_project_name = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_project_name.sizePolicy().hasHeightForWidth())
        self.label_project_name.setSizePolicy(sizePolicy)
        self.label_project_name.setMinimumSize(QtCore.QSize(87, 0))
        self.label_project_name.setMaximumSize(QtCore.QSize(237, 35))
        self.label_project_name.setStyleSheet("QLabel{\n"
"    max-width: 215px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_project_name.setScaledContents(False)
        self.label_project_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_project_name.setWordWrap(False)
        self.label_project_name.setObjectName("label_project_name")
        self.horizontalLayout_project_name.addWidget(self.label_project_name)
        self.lineEdit_project_name = QtWidgets.QLineEdit(self.frame_project_info)
        self.lineEdit_project_name.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_project_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_project_name.setSizePolicy(sizePolicy)
        self.lineEdit_project_name.setMinimumSize(QtCore.QSize(101, 0))
        self.lineEdit_project_name.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_project_name.setObjectName("lineEdit_project_name")
        self.horizontalLayout_project_name.addWidget(self.lineEdit_project_name)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_project_name)
        self.horizontalLayout_project_number = QtWidgets.QHBoxLayout()
        self.horizontalLayout_project_number.setObjectName("horizontalLayout_project_number")
        self.label_project_number = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_project_number.sizePolicy().hasHeightForWidth())
        self.label_project_number.setSizePolicy(sizePolicy)
        self.label_project_number.setMinimumSize(QtCore.QSize(87, 0))
        self.label_project_number.setMaximumSize(QtCore.QSize(237, 35))
        self.label_project_number.setStyleSheet("QLabel{\n"
"    max-width: 215px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_project_number.setScaledContents(False)
        self.label_project_number.setAlignment(QtCore.Qt.AlignCenter)
        self.label_project_number.setWordWrap(False)
        self.label_project_number.setObjectName("label_project_number")
        self.horizontalLayout_project_number.addWidget(self.label_project_number)
        self.lineEdit_project_number = QtWidgets.QLineEdit(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_project_number.sizePolicy().hasHeightForWidth())
        self.lineEdit_project_number.setSizePolicy(sizePolicy)
        self.lineEdit_project_number.setMinimumSize(QtCore.QSize(101, 0))
        self.lineEdit_project_number.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_project_number.setObjectName("lineEdit_project_number")
        self.horizontalLayout_project_number.addWidget(self.lineEdit_project_number)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_project_number)
        self.horizontalLayout_task_number = QtWidgets.QHBoxLayout()
        self.horizontalLayout_task_number.setObjectName("horizontalLayout_task_number")
        self.label_task_number = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_task_number.sizePolicy().hasHeightForWidth())
        self.label_task_number.setSizePolicy(sizePolicy)
        self.label_task_number.setMinimumSize(QtCore.QSize(87, 0))
        self.label_task_number.setMaximumSize(QtCore.QSize(237, 35))
        self.label_task_number.setStyleSheet("QLabel{\n"
"    max-width: 215px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_task_number.setScaledContents(False)
        self.label_task_number.setAlignment(QtCore.Qt.AlignCenter)
        self.label_task_number.setWordWrap(False)
        self.label_task_number.setObjectName("label_task_number")
        self.horizontalLayout_task_number.addWidget(self.label_task_number)
        self.lineEdit_task_number = QtWidgets.QLineEdit(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_task_number.sizePolicy().hasHeightForWidth())
        self.lineEdit_task_number.setSizePolicy(sizePolicy)
        self.lineEdit_task_number.setMinimumSize(QtCore.QSize(101, 0))
        self.lineEdit_task_number.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_task_number.setObjectName("lineEdit_task_number")
        self.horizontalLayout_task_number.addWidget(self.lineEdit_task_number)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_task_number)
        self.horizontalLayout_currency = QtWidgets.QHBoxLayout()
        self.horizontalLayout_currency.setObjectName("horizontalLayout_currency")
        self.checkBox_billable = QtWidgets.QCheckBox(self.frame_project_info)
        self.checkBox_billable.setStyleSheet("QCheckBox{\n"
"    max-width: 100px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"}\n"
"QCheckBox::indicator{\n"
"margin-left:5%; margin-right:5%;\n"
"width: 30px;\n"
"height: 30px;\n"
"}\n"
"\n"
"QCheckBox::indicator::unchecked{\n"
"    image: url(:/images/icons8-toggle-off-100.png);\n"
"\n"
"}\n"
"\n"
"QCheckBox::indicator::checked{\n"
"    image: url(:/images/icons8-toggle-on-100.png);\n"
"}\n"
"")
        self.checkBox_billable.setChecked(True)
        self.checkBox_billable.setObjectName("checkBox_billable")
        self.horizontalLayout_currency.addWidget(self.checkBox_billable)
        self.label_hourly_rate = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_hourly_rate.sizePolicy().hasHeightForWidth())
        self.label_hourly_rate.setSizePolicy(sizePolicy)
        self.label_hourly_rate.setMinimumSize(QtCore.QSize(87, 0))
        self.label_hourly_rate.setMaximumSize(QtCore.QSize(122, 35))
        self.label_hourly_rate.setStyleSheet("QLabel{\n"
"    max-width: 100px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_hourly_rate.setScaledContents(False)
        self.label_hourly_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hourly_rate.setWordWrap(False)
        self.label_hourly_rate.setObjectName("label_hourly_rate")
        self.horizontalLayout_currency.addWidget(self.label_hourly_rate)
        self.lineEdit_hourly_rate = QtWidgets.QLineEdit(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_hourly_rate.sizePolicy().hasHeightForWidth())
        self.lineEdit_hourly_rate.setSizePolicy(sizePolicy)
        self.lineEdit_hourly_rate.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_hourly_rate.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_hourly_rate.setObjectName("lineEdit_hourly_rate")
        self.horizontalLayout_currency.addWidget(self.lineEdit_hourly_rate)
        self.comboBox_currency = QtWidgets.QComboBox(self.frame_project_info)
        self.comboBox_currency.setMaximumSize(QtCore.QSize(122, 35))
        self.comboBox_currency.setStyleSheet("QComboBox{\n"
"    max-width: 100px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QComboBox::hover{\n"
"    background-color: rgb(182, 182, 182) ;\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.comboBox_currency.setObjectName("comboBox_currency")
        self.comboBox_currency.addItem("")
        self.comboBox_currency.addItem("")
        self.horizontalLayout_currency.addWidget(self.comboBox_currency)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_currency)
        self.horizontalLayout_project_manager = QtWidgets.QHBoxLayout()
        self.horizontalLayout_project_manager.setObjectName("horizontalLayout_project_manager")
        self.label_project_manager = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_project_manager.sizePolicy().hasHeightForWidth())
        self.label_project_manager.setSizePolicy(sizePolicy)
        self.label_project_manager.setMinimumSize(QtCore.QSize(87, 0))
        self.label_project_manager.setMaximumSize(QtCore.QSize(237, 35))
        self.label_project_manager.setStyleSheet("QLabel{\n"
"    max-width: 215px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_project_manager.setScaledContents(False)
        self.label_project_manager.setAlignment(QtCore.Qt.AlignCenter)
        self.label_project_manager.setWordWrap(False)
        self.label_project_manager.setObjectName("label_project_manager")
        self.horizontalLayout_project_manager.addWidget(self.label_project_manager)
        self.lineEdit_project_manager = QtWidgets.QLineEdit(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_project_manager.sizePolicy().hasHeightForWidth())
        self.lineEdit_project_manager.setSizePolicy(sizePolicy)
        self.lineEdit_project_manager.setMinimumSize(QtCore.QSize(101, 0))
        self.lineEdit_project_manager.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_project_manager.setObjectName("lineEdit_project_manager")
        self.horizontalLayout_project_manager.addWidget(self.lineEdit_project_manager)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_project_manager)
        self.horizontalLayout_client_contact = QtWidgets.QHBoxLayout()
        self.horizontalLayout_client_contact.setObjectName("horizontalLayout_client_contact")
        self.label_client_contact = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_client_contact.sizePolicy().hasHeightForWidth())
        self.label_client_contact.setSizePolicy(sizePolicy)
        self.label_client_contact.setMinimumSize(QtCore.QSize(87, 0))
        self.label_client_contact.setMaximumSize(QtCore.QSize(237, 35))
        self.label_client_contact.setStyleSheet("QLabel{\n"
"    max-width: 215px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_client_contact.setScaledContents(False)
        self.label_client_contact.setAlignment(QtCore.Qt.AlignCenter)
        self.label_client_contact.setWordWrap(False)
        self.label_client_contact.setObjectName("label_client_contact")
        self.horizontalLayout_client_contact.addWidget(self.label_client_contact)
        self.lineEdit_client_contact = QtWidgets.QLineEdit(self.frame_project_info)
        self.lineEdit_client_contact.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_client_contact.sizePolicy().hasHeightForWidth())
        self.lineEdit_client_contact.setSizePolicy(sizePolicy)
        self.lineEdit_client_contact.setMinimumSize(QtCore.QSize(101, 0))
        self.lineEdit_client_contact.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_client_contact.setObjectName("lineEdit_client_contact")
        self.horizontalLayout_client_contact.addWidget(self.lineEdit_client_contact)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_client_contact)
        self.horizontalLayout_additional_information = QtWidgets.QHBoxLayout()
        self.horizontalLayout_additional_information.setObjectName("horizontalLayout_additional_information")
        self.label_additional_information = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_additional_information.sizePolicy().hasHeightForWidth())
        self.label_additional_information.setSizePolicy(sizePolicy)
        self.label_additional_information.setMinimumSize(QtCore.QSize(87, 0))
        self.label_additional_information.setMaximumSize(QtCore.QSize(237, 35))
        self.label_additional_information.setStyleSheet("QLabel{\n"
"    max-width: 215px;\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_additional_information.setScaledContents(False)
        self.label_additional_information.setAlignment(QtCore.Qt.AlignCenter)
        self.label_additional_information.setWordWrap(False)
        self.label_additional_information.setObjectName("label_additional_information")
        self.horizontalLayout_additional_information.addWidget(self.label_additional_information)
        self.lineEdit_additional_information = QtWidgets.QLineEdit(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_additional_information.sizePolicy().hasHeightForWidth())
        self.lineEdit_additional_information.setSizePolicy(sizePolicy)
        self.lineEdit_additional_information.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_additional_information.setObjectName("lineEdit_additional_information")
        self.horizontalLayout_additional_information.addWidget(self.lineEdit_additional_information)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_additional_information)
        self.horizontalLayout_project_info.addLayout(self.verticalLayout_project_info)
        self.verticalLayout.addLayout(self.horizontalLayout_project_info)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_edit = QtWidgets.QPushButton(self.frame_project_info)
        self.pushButton_edit.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(206, 232, 255) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 144, 144);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_edit.setObjectName("pushButton_edit")
        self.horizontalLayout.addWidget(self.pushButton_edit)
        self.pushButton_cancel = QtWidgets.QPushButton(self.frame_project_info)
        self.pushButton_cancel.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(206, 232, 255) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 144, 144);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_project_info, 0, 0, 1, 1)

        self.retranslateUi(ProjectInput_edit_dialog)
        self.checkBox_billable.stateChanged['int'].connect(ProjectInput_edit_dialog.billable_changed)
        self.pushButton_edit.clicked.connect(ProjectInput_edit_dialog.edit_project)
        self.pushButton_cancel.clicked.connect(ProjectInput_edit_dialog.close)
        QtCore.QMetaObject.connectSlotsByName(ProjectInput_edit_dialog)

    def retranslateUi(self, ProjectInput_edit_dialog):
        _translate = QtCore.QCoreApplication.translate
        ProjectInput_edit_dialog.setWindowTitle(_translate("ProjectInput_edit_dialog", "Dialog"))
        self.label_client.setText(_translate("ProjectInput_edit_dialog", "Client"))
        self.label_project_name.setText(_translate("ProjectInput_edit_dialog", "Project Name"))
        self.label_project_number.setText(_translate("ProjectInput_edit_dialog", "Project Number"))
        self.label_task_number.setText(_translate("ProjectInput_edit_dialog", "Task Number"))
        self.checkBox_billable.setText(_translate("ProjectInput_edit_dialog", "Billable"))
        self.label_hourly_rate.setText(_translate("ProjectInput_edit_dialog", "Hourly Rate"))
        self.comboBox_currency.setItemText(0, _translate("ProjectInput_edit_dialog", "€ Euro"))
        self.comboBox_currency.setItemText(1, _translate("ProjectInput_edit_dialog", "$ Dollar"))
        self.label_project_manager.setText(_translate("ProjectInput_edit_dialog", "Project Manager"))
        self.label_client_contact.setText(_translate("ProjectInput_edit_dialog", "Client Contact"))
        self.label_additional_information.setText(_translate("ProjectInput_edit_dialog", "Additional Information"))
        self.pushButton_edit.setText(_translate("ProjectInput_edit_dialog", "Edit"))
        self.pushButton_cancel.setText(_translate("ProjectInput_edit_dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProjectInput_edit_dialog = QtWidgets.QDialog()
    ui = Ui_ProjectInput_edit_dialog()
    ui.setupUi(ProjectInput_edit_dialog)
    ProjectInput_edit_dialog.show()
    sys.exit(app.exec_())
