# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hour_Registry_DH_dialog_QT.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DailyHours_edit_dialog(object):
    def setupUi(self, DailyHours_edit_dialog):
        DailyHours_edit_dialog.setObjectName("DailyHours_edit_dialog")
        DailyHours_edit_dialog.resize(502, 417)
        self.gridLayout = QtWidgets.QGridLayout(DailyHours_edit_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_date = QtWidgets.QHBoxLayout()
        self.horizontalLayout_date.setObjectName("horizontalLayout_date")
        self.pushButton_date = QtWidgets.QPushButton(DailyHours_edit_dialog)
        self.pushButton_date.setStyleSheet("QPushButton{\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(174, 174, 174);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_date.setObjectName("pushButton_date")
        self.horizontalLayout_date.addWidget(self.pushButton_date)
        self.dateEdit = QtWidgets.QDateEdit(DailyHours_edit_dialog)
        self.dateEdit.setMinimumSize(QtCore.QSize(130, 0))
        self.dateEdit.setStyleSheet("QDateEdit{\n"
"    background-color:beige;    \n"
"    border-style:outset;\n"
"    border-width: 4px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(220, 247, 255);\n"
"    font: 14px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"\n"
"")
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_date.addWidget(self.dateEdit)
        self.gridLayout.addLayout(self.horizontalLayout_date, 0, 0, 1, 2)
        self.horizontalLayout_start = QtWidgets.QHBoxLayout()
        self.horizontalLayout_start.setObjectName("horizontalLayout_start")
        self.pushButton_start = QtWidgets.QPushButton(DailyHours_edit_dialog)
        self.pushButton_start.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_start.setStyleSheet("QPushButton{\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(174, 174, 174);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_start.addWidget(self.pushButton_start)
        self.timeEdit_start = QtWidgets.QTimeEdit(DailyHours_edit_dialog)
        self.timeEdit_start.setStyleSheet("QTimeEdit{\n"
"    background-color:beige;    \n"
"    border-style:outset;\n"
"    border-width: 4px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(220, 247, 255);\n"
"    font: 14px;\n"
"    padding: 6px;\n"
"}")
        self.timeEdit_start.setCalendarPopup(False)
        self.timeEdit_start.setObjectName("timeEdit_start")
        self.horizontalLayout_start.addWidget(self.timeEdit_start)
        self.gridLayout.addLayout(self.horizontalLayout_start, 1, 0, 1, 2)
        self.horizontalLayout_end = QtWidgets.QHBoxLayout()
        self.horizontalLayout_end.setObjectName("horizontalLayout_end")
        self.pushButton_end = QtWidgets.QPushButton(DailyHours_edit_dialog)
        self.pushButton_end.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_end.setStyleSheet("QPushButton{\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(174, 174, 174);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_end.setObjectName("pushButton_end")
        self.horizontalLayout_end.addWidget(self.pushButton_end)
        self.timeEdit_end = QtWidgets.QTimeEdit(DailyHours_edit_dialog)
        self.timeEdit_end.setStyleSheet("QTimeEdit{\n"
"    background-color:beige;    \n"
"    border-style:outset;\n"
"    border-width: 4px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(220, 247, 255);\n"
"    font: 14px;\n"
"    padding: 6px;\n"
"}")
        self.timeEdit_end.setObjectName("timeEdit_end")
        self.horizontalLayout_end.addWidget(self.timeEdit_end)
        self.gridLayout.addLayout(self.horizontalLayout_end, 2, 0, 1, 2)
        self.horizontalLayout_increment = QtWidgets.QHBoxLayout()
        self.horizontalLayout_increment.setObjectName("horizontalLayout_increment")
        self.label_Increment = QtWidgets.QLabel(DailyHours_edit_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Increment.sizePolicy().hasHeightForWidth())
        self.label_Increment.setSizePolicy(sizePolicy)
        self.label_Increment.setMinimumSize(QtCore.QSize(0, 0))
        self.label_Increment.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_Increment.setStyleSheet("QLabel{\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.label_Increment.setScaledContents(False)
        self.label_Increment.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Increment.setWordWrap(False)
        self.label_Increment.setObjectName("label_Increment")
        self.horizontalLayout_increment.addWidget(self.label_Increment)
        self.pushButton_15min = QtWidgets.QPushButton(DailyHours_edit_dialog)
        self.pushButton_15min.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_15min.setMaximumSize(QtCore.QSize(16777215, 35))
        self.pushButton_15min.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(206, 232, 255) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color:rgb(255, 144, 144);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_15min.setObjectName("pushButton_15min")
        self.horizontalLayout_increment.addWidget(self.pushButton_15min)
        self.pushButton_1h = QtWidgets.QPushButton(DailyHours_edit_dialog)
        self.pushButton_1h.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_1h.setMaximumSize(QtCore.QSize(16777215, 35))
        self.pushButton_1h.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(206, 232, 255) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color:rgb(255, 144, 144);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_1h.setObjectName("pushButton_1h")
        self.horizontalLayout_increment.addWidget(self.pushButton_1h)
        self.gridLayout.addLayout(self.horizontalLayout_increment, 3, 0, 1, 2)
        self.horizontalLayout_duration = QtWidgets.QHBoxLayout()
        self.horizontalLayout_duration.setObjectName("horizontalLayout_duration")
        self.label_duration = QtWidgets.QLabel(DailyHours_edit_dialog)
        self.label_duration.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_duration.sizePolicy().hasHeightForWidth())
        self.label_duration.setSizePolicy(sizePolicy)
        self.label_duration.setMinimumSize(QtCore.QSize(0, 0))
        self.label_duration.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_duration.setStyleSheet("QLabel{\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.label_duration.setScaledContents(False)
        self.label_duration.setAlignment(QtCore.Qt.AlignCenter)
        self.label_duration.setWordWrap(False)
        self.label_duration.setObjectName("label_duration")
        self.horizontalLayout_duration.addWidget(self.label_duration)
        self.label_duration_time = QtWidgets.QLabel(DailyHours_edit_dialog)
        self.label_duration_time.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_duration_time.sizePolicy().hasHeightForWidth())
        self.label_duration_time.setSizePolicy(sizePolicy)
        self.label_duration_time.setMinimumSize(QtCore.QSize(0, 0))
        self.label_duration_time.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_duration_time.setStyleSheet("QLabel{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.label_duration_time.setText("")
        self.label_duration_time.setScaledContents(False)
        self.label_duration_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_duration_time.setWordWrap(False)
        self.label_duration_time.setObjectName("label_duration_time")
        self.horizontalLayout_duration.addWidget(self.label_duration_time)
        self.gridLayout.addLayout(self.horizontalLayout_duration, 4, 0, 1, 2)
        self.label_project = QtWidgets.QLabel(DailyHours_edit_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_project.sizePolicy().hasHeightForWidth())
        self.label_project.setSizePolicy(sizePolicy)
        self.label_project.setMinimumSize(QtCore.QSize(0, 0))
        self.label_project.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_project.setStyleSheet("QLabel{\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.label_project.setScaledContents(False)
        self.label_project.setAlignment(QtCore.Qt.AlignCenter)
        self.label_project.setWordWrap(False)
        self.label_project.setObjectName("label_project")
        self.gridLayout.addWidget(self.label_project, 5, 0, 1, 1)
        self.comboBox_project_select = QtWidgets.QComboBox(DailyHours_edit_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_project_select.sizePolicy().hasHeightForWidth())
        self.comboBox_project_select.setSizePolicy(sizePolicy)
        self.comboBox_project_select.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_project_select.setStyleSheet("QComboBox{\n"
"    background-color: rgb(245, 245, 220);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}\n"
"QComboBox::hover{\n"
"    background-color:rgb(234, 234, 210) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.comboBox_project_select.setObjectName("comboBox_project_select")
        self.gridLayout.addWidget(self.comboBox_project_select, 5, 1, 1, 1)
        self.horizontalLayout_task = QtWidgets.QHBoxLayout()
        self.horizontalLayout_task.setObjectName("horizontalLayout_task")
        self.label_task = QtWidgets.QLabel(DailyHours_edit_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_task.sizePolicy().hasHeightForWidth())
        self.label_task.setSizePolicy(sizePolicy)
        self.label_task.setMinimumSize(QtCore.QSize(0, 0))
        self.label_task.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_task.setStyleSheet("QLabel{\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.label_task.setScaledContents(False)
        self.label_task.setAlignment(QtCore.Qt.AlignCenter)
        self.label_task.setWordWrap(False)
        self.label_task.setObjectName("label_task")
        self.horizontalLayout_task.addWidget(self.label_task)
        self.comboBox_task_select = QtWidgets.QComboBox(DailyHours_edit_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_task_select.sizePolicy().hasHeightForWidth())
        self.comboBox_task_select.setSizePolicy(sizePolicy)
        self.comboBox_task_select.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_task_select.setStyleSheet("QComboBox{\n"
"    background-color: rgb(245, 245, 220);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}\n"
"QComboBox::hover{\n"
"    background-color:rgb(234, 234, 210) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.comboBox_task_select.setObjectName("comboBox_task_select")
        self.horizontalLayout_task.addWidget(self.comboBox_task_select)
        self.gridLayout.addLayout(self.horizontalLayout_task, 6, 0, 1, 2)
        self.horizontalLayout_additional_information = QtWidgets.QHBoxLayout()
        self.horizontalLayout_additional_information.setObjectName("horizontalLayout_additional_information")
        self.label_additional_information = QtWidgets.QLabel(DailyHours_edit_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_additional_information.sizePolicy().hasHeightForWidth())
        self.label_additional_information.setSizePolicy(sizePolicy)
        self.label_additional_information.setMinimumSize(QtCore.QSize(0, 0))
        self.label_additional_information.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_additional_information.setStyleSheet("QLabel{\n"
"    background-color: rgb(202, 202, 202);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.label_additional_information.setScaledContents(False)
        self.label_additional_information.setAlignment(QtCore.Qt.AlignCenter)
        self.label_additional_information.setWordWrap(False)
        self.label_additional_information.setObjectName("label_additional_information")
        self.horizontalLayout_additional_information.addWidget(self.label_additional_information)
        self.lineEdit_additional_information = QtWidgets.QLineEdit(DailyHours_edit_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_additional_information.sizePolicy().hasHeightForWidth())
        self.lineEdit_additional_information.setSizePolicy(sizePolicy)
        self.lineEdit_additional_information.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_additional_information.setStyleSheet("QLineEdit{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 11px;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_additional_information.setObjectName("lineEdit_additional_information")
        self.horizontalLayout_additional_information.addWidget(self.lineEdit_additional_information)
        self.gridLayout.addLayout(self.horizontalLayout_additional_information, 7, 0, 1, 2)
        self.horizontalLayout_edit = QtWidgets.QHBoxLayout()
        self.horizontalLayout_edit.setObjectName("horizontalLayout_edit")
        self.pushButton_edit_table = QtWidgets.QPushButton(DailyHours_edit_dialog)
        self.pushButton_edit_table.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_edit_table.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(206, 232, 255) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color:rgb(255, 144, 144);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_edit_table.setObjectName("pushButton_edit_table")
        self.horizontalLayout_edit.addWidget(self.pushButton_edit_table)
        self.pushButton_cancel = QtWidgets.QPushButton(DailyHours_edit_dialog)
        self.pushButton_cancel.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_cancel.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(206, 232, 255) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color:rgb(255, 144, 144);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_edit.addWidget(self.pushButton_cancel)
        self.gridLayout.addLayout(self.horizontalLayout_edit, 8, 0, 1, 2)

        self.retranslateUi(DailyHours_edit_dialog)
        self.pushButton_date.clicked.connect(DailyHours_edit_dialog.date_now) # type: ignore
        self.pushButton_end.clicked.connect(DailyHours_edit_dialog.end_now) # type: ignore
        self.pushButton_start.clicked.connect(DailyHours_edit_dialog.start_now) # type: ignore
        self.pushButton_cancel.clicked.connect(DailyHours_edit_dialog.close) # type: ignore
        self.pushButton_edit_table.clicked.connect(DailyHours_edit_dialog.edit_daily) # type: ignore
        self.comboBox_project_select.currentTextChanged['QString'].connect(DailyHours_edit_dialog.project_select_changed) # type: ignore
        self.timeEdit_start.userTimeChanged['QTime'].connect(DailyHours_edit_dialog.duration) # type: ignore
        self.timeEdit_end.userTimeChanged['QTime'].connect(DailyHours_edit_dialog.duration) # type: ignore
        self.pushButton_15min.clicked.connect(DailyHours_edit_dialog.add_min) # type: ignore
        self.pushButton_1h.clicked.connect(DailyHours_edit_dialog.add_hour) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DailyHours_edit_dialog)

    def retranslateUi(self, DailyHours_edit_dialog):
        _translate = QtCore.QCoreApplication.translate
        DailyHours_edit_dialog.setWindowTitle(_translate("DailyHours_edit_dialog", "Dialog"))
        self.pushButton_date.setText(_translate("DailyHours_edit_dialog", "Date"))
        self.pushButton_start.setText(_translate("DailyHours_edit_dialog", "Start "))
        self.pushButton_end.setText(_translate("DailyHours_edit_dialog", "End"))
        self.label_Increment.setText(_translate("DailyHours_edit_dialog", "Add Increments"))
        self.pushButton_15min.setToolTip(_translate("DailyHours_edit_dialog", "Click to get Current Time"))
        self.pushButton_15min.setText(_translate("DailyHours_edit_dialog", "+15 min"))
        self.pushButton_1h.setToolTip(_translate("DailyHours_edit_dialog", "Click to get Current Time"))
        self.pushButton_1h.setText(_translate("DailyHours_edit_dialog", "+1 h"))
        self.label_duration.setText(_translate("DailyHours_edit_dialog", "Duration"))
        self.label_project.setText(_translate("DailyHours_edit_dialog", "Project"))
        self.label_task.setText(_translate("DailyHours_edit_dialog", "Task"))
        self.label_additional_information.setText(_translate("DailyHours_edit_dialog", "Comment"))
        self.lineEdit_additional_information.setToolTip(_translate("DailyHours_edit_dialog", "This comment will be added to the \"Day\" comment column in the Oracle export. \n"
" Comments of similar Task Name and day will be concatenated. "))
        self.pushButton_edit_table.setText(_translate("DailyHours_edit_dialog", "Edit Table"))
        self.pushButton_cancel.setText(_translate("DailyHours_edit_dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DailyHours_edit_dialog = QtWidgets.QDialog()
    ui = Ui_DailyHours_edit_dialog()
    ui.setupUi(DailyHours_edit_dialog)
    DailyHours_edit_dialog.show()
    sys.exit(app.exec_())
