# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hour_Registry_QT.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(892, 857)
        MainWindow.setStyleSheet("background-color: rgb(255, 230, 230);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("QTabBar {\n"
"alignment: center;\n"
"}\n"
"QTabWidget::pane {\n"
"    background-color: transparent;\n"
"    border:0;\n"
"\n"
"}\n"
"QTabBar::tab{\n"
"    background-color:rgb(228, 228, 228);\n"
"    color: rgb(145, 145, 145);\n"
"    font:bold;\n"
"    border-radius: 5px;\n"
"    min-width: 40px;\n"
"    width: 200px;\n"
"    height: 35px;    \n"
"}\n"
"QTabBar::tab:hover{\n"
"    background-color:rgb(228, 228, 228);\n"
"    color:rgb(0, 0, 0);\n"
"    font:bold;\n"
"    border-radius: 5px;\n"
"    min-width: 40px;\n"
"    width: 200px;\n"
"    height: 35px;    \n"
"}\n"
"QTabBar::tab:selected {\n"
"    background:rgb(145, 145, 145);\n"
"    color: rgb(0, 0, 0);\n"
"    font: bold;\n"
"    border-radius: 5px;\n"
"    min-width: 40px;\n"
"    width: 200px;    \n"
"height: 35px;\n"
"}\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.Project_Input = QtWidgets.QWidget()
        self.Project_Input.setObjectName("Project_Input")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Project_Input)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_project_input = QtWidgets.QVBoxLayout()
        self.verticalLayout_project_input.setObjectName("verticalLayout_project_input")
        self.frame_project_info = QtWidgets.QFrame(self.Project_Input)
        self.frame_project_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_project_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_project_info.setObjectName("frame_project_info")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_project_info)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_project_info = QtWidgets.QHBoxLayout()
        self.horizontalLayout_project_info.setObjectName("horizontalLayout_project_info")
        self.verticalLayout_project_info = QtWidgets.QVBoxLayout()
        self.verticalLayout_project_info.setObjectName("verticalLayout_project_info")
        self.horizontalLayout1_client = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_client.setObjectName("horizontalLayout1_client")
        self.label_PI_client = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_PI_client.sizePolicy().hasHeightForWidth())
        self.label_PI_client.setSizePolicy(sizePolicy)
        self.label_PI_client.setMinimumSize(QtCore.QSize(107, 0))
        self.label_PI_client.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_PI_client.setStyleSheet("QLabel{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_PI_client.setScaledContents(False)
        self.label_PI_client.setAlignment(QtCore.Qt.AlignCenter)
        self.label_PI_client.setWordWrap(False)
        self.label_PI_client.setObjectName("label_PI_client")
        self.horizontalLayout1_client.addWidget(self.label_PI_client)
        self.lineEdit_PI_client = QtWidgets.QLineEdit(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_PI_client.sizePolicy().hasHeightForWidth())
        self.lineEdit_PI_client.setSizePolicy(sizePolicy)
        self.lineEdit_PI_client.setMinimumSize(QtCore.QSize(101, 0))
        self.lineEdit_PI_client.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_PI_client.setObjectName("lineEdit_PI_client")
        self.horizontalLayout1_client.addWidget(self.lineEdit_PI_client)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout1_client)
        self.horizontalLayout_p_name = QtWidgets.QHBoxLayout()
        self.horizontalLayout_p_name.setObjectName("horizontalLayout_p_name")
        self.label_PI_p_name = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_PI_p_name.sizePolicy().hasHeightForWidth())
        self.label_PI_p_name.setSizePolicy(sizePolicy)
        self.label_PI_p_name.setMinimumSize(QtCore.QSize(107, 0))
        self.label_PI_p_name.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_PI_p_name.setStyleSheet("QLabel{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_PI_p_name.setScaledContents(False)
        self.label_PI_p_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_PI_p_name.setWordWrap(False)
        self.label_PI_p_name.setObjectName("label_PI_p_name")
        self.horizontalLayout_p_name.addWidget(self.label_PI_p_name)
        self.lineEdit_PI_p_name = QtWidgets.QLineEdit(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_PI_p_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_PI_p_name.setSizePolicy(sizePolicy)
        self.lineEdit_PI_p_name.setMinimumSize(QtCore.QSize(101, 0))
        self.lineEdit_PI_p_name.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_PI_p_name.setObjectName("lineEdit_PI_p_name")
        self.horizontalLayout_p_name.addWidget(self.lineEdit_PI_p_name)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_p_name)
        self.horizontalLayout_p_number = QtWidgets.QHBoxLayout()
        self.horizontalLayout_p_number.setObjectName("horizontalLayout_p_number")
        self.label_PI_p_number = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_PI_p_number.sizePolicy().hasHeightForWidth())
        self.label_PI_p_number.setSizePolicy(sizePolicy)
        self.label_PI_p_number.setMinimumSize(QtCore.QSize(107, 0))
        self.label_PI_p_number.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_PI_p_number.setStyleSheet("QLabel{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_PI_p_number.setScaledContents(False)
        self.label_PI_p_number.setAlignment(QtCore.Qt.AlignCenter)
        self.label_PI_p_number.setWordWrap(False)
        self.label_PI_p_number.setObjectName("label_PI_p_number")
        self.horizontalLayout_p_number.addWidget(self.label_PI_p_number)
        self.lineEdit_PI_p_number = QtWidgets.QLineEdit(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_PI_p_number.sizePolicy().hasHeightForWidth())
        self.lineEdit_PI_p_number.setSizePolicy(sizePolicy)
        self.lineEdit_PI_p_number.setMinimumSize(QtCore.QSize(101, 0))
        self.lineEdit_PI_p_number.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_PI_p_number.setObjectName("lineEdit_PI_p_number")
        self.horizontalLayout_p_number.addWidget(self.lineEdit_PI_p_number)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_p_number)
        self.horizontalLayout_t_number = QtWidgets.QHBoxLayout()
        self.horizontalLayout_t_number.setObjectName("horizontalLayout_t_number")
        self.label_PI_t_number = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_PI_t_number.sizePolicy().hasHeightForWidth())
        self.label_PI_t_number.setSizePolicy(sizePolicy)
        self.label_PI_t_number.setMinimumSize(QtCore.QSize(107, 0))
        self.label_PI_t_number.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_PI_t_number.setStyleSheet("QLabel{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_PI_t_number.setScaledContents(False)
        self.label_PI_t_number.setAlignment(QtCore.Qt.AlignCenter)
        self.label_PI_t_number.setWordWrap(False)
        self.label_PI_t_number.setObjectName("label_PI_t_number")
        self.horizontalLayout_t_number.addWidget(self.label_PI_t_number)
        self.lineEdit_PI_t_number = QtWidgets.QLineEdit(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_PI_t_number.sizePolicy().hasHeightForWidth())
        self.lineEdit_PI_t_number.setSizePolicy(sizePolicy)
        self.lineEdit_PI_t_number.setMinimumSize(QtCore.QSize(101, 0))
        self.lineEdit_PI_t_number.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_PI_t_number.setObjectName("lineEdit_PI_t_number")
        self.horizontalLayout_t_number.addWidget(self.lineEdit_PI_t_number)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_t_number)
        self.horizontalLayout_currency = QtWidgets.QHBoxLayout()
        self.horizontalLayout_currency.setObjectName("horizontalLayout_currency")
        self.label_PI_rate = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_PI_rate.sizePolicy().hasHeightForWidth())
        self.label_PI_rate.setSizePolicy(sizePolicy)
        self.label_PI_rate.setMinimumSize(QtCore.QSize(107, 0))
        self.label_PI_rate.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_PI_rate.setStyleSheet("QLabel{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_PI_rate.setScaledContents(False)
        self.label_PI_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_PI_rate.setWordWrap(False)
        self.label_PI_rate.setObjectName("label_PI_rate")
        self.horizontalLayout_currency.addWidget(self.label_PI_rate)
        self.lineEdit_PI_rate = QtWidgets.QLineEdit(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_PI_rate.sizePolicy().hasHeightForWidth())
        self.lineEdit_PI_rate.setSizePolicy(sizePolicy)
        self.lineEdit_PI_rate.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_PI_rate.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_PI_rate.setObjectName("lineEdit_PI_rate")
        self.horizontalLayout_currency.addWidget(self.lineEdit_PI_rate)
        self.comboBox_PI_currency = QtWidgets.QComboBox(self.frame_project_info)
        self.comboBox_PI_currency.setMaximumSize(QtCore.QSize(16777215, 35))
        self.comboBox_PI_currency.setStyleSheet("QComboBox{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QComboBox::hover{\n"
"    background-color:rgb(206, 232, 255) ;\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 144, 144);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.comboBox_PI_currency.setObjectName("comboBox_PI_currency")
        self.comboBox_PI_currency.addItem("")
        self.comboBox_PI_currency.addItem("")
        self.horizontalLayout_currency.addWidget(self.comboBox_PI_currency)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_currency)
        self.horizontalLayout_add_info = QtWidgets.QHBoxLayout()
        self.horizontalLayout_add_info.setObjectName("horizontalLayout_add_info")
        self.label_PI_add_info = QtWidgets.QLabel(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_PI_add_info.sizePolicy().hasHeightForWidth())
        self.label_PI_add_info.setSizePolicy(sizePolicy)
        self.label_PI_add_info.setMinimumSize(QtCore.QSize(107, 0))
        self.label_PI_add_info.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_PI_add_info.setStyleSheet("QLabel{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.label_PI_add_info.setScaledContents(False)
        self.label_PI_add_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_PI_add_info.setWordWrap(False)
        self.label_PI_add_info.setObjectName("label_PI_add_info")
        self.horizontalLayout_add_info.addWidget(self.label_PI_add_info)
        self.lineEdit_PI_add_info = QtWidgets.QLineEdit(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_PI_add_info.sizePolicy().hasHeightForWidth())
        self.lineEdit_PI_add_info.setSizePolicy(sizePolicy)
        self.lineEdit_PI_add_info.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_PI_add_info.setObjectName("lineEdit_PI_add_info")
        self.horizontalLayout_add_info.addWidget(self.lineEdit_PI_add_info)
        self.verticalLayout_project_info.addLayout(self.horizontalLayout_add_info)
        self.horizontalLayout_project_info.addLayout(self.verticalLayout_project_info)
        self.pushButton_PI_clear_input = QtWidgets.QPushButton(self.frame_project_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_PI_clear_input.sizePolicy().hasHeightForWidth())
        self.pushButton_PI_clear_input.setSizePolicy(sizePolicy)
        self.pushButton_PI_clear_input.setMinimumSize(QtCore.QSize(73, 210))
        self.pushButton_PI_clear_input.setMaximumSize(QtCore.QSize(65, 16777215))
        self.pushButton_PI_clear_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_PI_clear_input.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    min-width: 3em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(255, 144, 144);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color:rgb(255, 144, 144);\n"
"    font: bold 14px;\n"
"    min-width: 3em;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_PI_clear_input.setObjectName("pushButton_PI_clear_input")
        self.horizontalLayout_project_info.addWidget(self.pushButton_PI_clear_input)
        self.gridLayout_6.addLayout(self.horizontalLayout_project_info, 0, 0, 1, 1)
        self.verticalLayout_project_input.addWidget(self.frame_project_info)
        self.pushButton_PI_add_project = QtWidgets.QPushButton(self.Project_Input)
        self.pushButton_PI_add_project.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(206, 232, 255) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 144, 144);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_PI_add_project.setObjectName("pushButton_PI_add_project")
        self.verticalLayout_project_input.addWidget(self.pushButton_PI_add_project)
        self.frame_project_overview = QtWidgets.QFrame(self.Project_Input)
        self.frame_project_overview.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_project_overview.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_project_overview.setObjectName("frame_project_overview")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_project_overview)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_project_overview = QtWidgets.QVBoxLayout()
        self.verticalLayout_project_overview.setObjectName("verticalLayout_project_overview")
        self.lineEdit_PI_search_table = QtWidgets.QLineEdit(self.frame_project_overview)
        self.lineEdit_PI_search_table.setStyleSheet("QLineEdit{\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.lineEdit_PI_search_table.setObjectName("lineEdit_PI_search_table")
        self.verticalLayout_project_overview.addWidget(self.lineEdit_PI_search_table)
        self.tableView_PI = QtWidgets.QTableView(self.frame_project_overview)
        self.tableView_PI.setMinimumSize(QtCore.QSize(186, 0))
        self.tableView_PI.setAutoFillBackground(True)
        self.tableView_PI.setStyleSheet("QTableView{\n"
"background-color: white;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"font:14px;\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"")
        self.tableView_PI.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView_PI.setAlternatingRowColors(True)
        self.tableView_PI.setSortingEnabled(True)
        self.tableView_PI.setObjectName("tableView_PI")
        self.tableView_PI.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView_PI.horizontalHeader().setDefaultSectionSize(200)
        self.tableView_PI.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_project_overview.addWidget(self.tableView_PI)
        self.horizontalLayout_table_delete = QtWidgets.QHBoxLayout()
        self.horizontalLayout_table_delete.setObjectName("horizontalLayout_table_delete")
        self.comboBox_PI_project_del = QtWidgets.QComboBox(self.frame_project_overview)
        self.comboBox_PI_project_del.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_PI_project_del.setStyleSheet("QComboBox{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"\n"
"    border-width: 4px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: 14px;\n"
"\n"
"    padding: 6px;\n"
"}\n"
"QComboBox::hover{\n"
"    background-color:beige;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.comboBox_PI_project_del.setObjectName("comboBox_PI_project_del")
        self.comboBox_PI_project_del.addItem("")
        self.horizontalLayout_table_delete.addWidget(self.comboBox_PI_project_del)
        self.pushButton_PI_delete_project = QtWidgets.QPushButton(self.frame_project_overview)
        self.pushButton_PI_delete_project.setMinimumSize(QtCore.QSize(192, 0))
        self.pushButton_PI_delete_project.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(255, 144, 144);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color:rgb(255, 144, 144);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_PI_delete_project.setObjectName("pushButton_PI_delete_project")
        self.horizontalLayout_table_delete.addWidget(self.pushButton_PI_delete_project)
        self.verticalLayout_project_overview.addLayout(self.horizontalLayout_table_delete)
        self.gridLayout_7.addLayout(self.verticalLayout_project_overview, 0, 0, 1, 1)
        self.verticalLayout_project_input.addWidget(self.frame_project_overview)
        self.gridLayout_2.addLayout(self.verticalLayout_project_input, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Project_Input, "")
        self.Daily_Hours = QtWidgets.QWidget()
        self.Daily_Hours.setObjectName("Daily_Hours")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.Daily_Hours)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.frame_table_daily_hours = QtWidgets.QFrame(self.Daily_Hours)
        self.frame_table_daily_hours.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_table_daily_hours.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_table_daily_hours.setObjectName("frame_table_daily_hours")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_table_daily_hours)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tableView_DH = QtWidgets.QTableView(self.frame_table_daily_hours)
        self.tableView_DH.setAutoFillBackground(True)
        self.tableView_DH.setStyleSheet("QTableView{\n"
"background-color:white;    \n"
"border-style:outset;\n"
"\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.tableView_DH.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView_DH.setAlternatingRowColors(True)
        self.tableView_DH.setSortingEnabled(True)
        self.tableView_DH.setObjectName("tableView_DH")
        self.tableView_DH.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView_DH.horizontalHeader().setDefaultSectionSize(200)
        self.gridLayout_9.addWidget(self.tableView_DH, 1, 0, 1, 1)
        self.lineEdit_DH_search_table = QtWidgets.QLineEdit(self.frame_table_daily_hours)
        self.lineEdit_DH_search_table.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_DH_search_table.setObjectName("lineEdit_DH_search_table")
        self.gridLayout_9.addWidget(self.lineEdit_DH_search_table, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame_table_daily_hours, 1, 0, 1, 1)
        self.frame_dh_operations = QtWidgets.QFrame(self.Daily_Hours)
        self.frame_dh_operations.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_dh_operations.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_dh_operations.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_dh_operations.setObjectName("frame_dh_operations")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_dh_operations)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_DH_sum_up = QtWidgets.QPushButton(self.frame_dh_operations)
        self.pushButton_DH_sum_up.setMinimumSize(QtCore.QSize(192, 0))
        self.pushButton_DH_sum_up.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font:14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(206, 232, 255) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color:rgb(255, 144, 144);\n"
"\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_DH_sum_up.setObjectName("pushButton_DH_sum_up")
        self.gridLayout_8.addWidget(self.pushButton_DH_sum_up, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dateEdit_DH_remove_time_interval = QtWidgets.QDateEdit(self.frame_dh_operations)
        self.dateEdit_DH_remove_time_interval.setStyleSheet("QDateEdit{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 4px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: 14px;\n"
"\n"
"    padding: 6px;\n"
"}")
        self.dateEdit_DH_remove_time_interval.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit_DH_remove_time_interval.setCalendarPopup(True)
        self.dateEdit_DH_remove_time_interval.setObjectName("dateEdit_DH_remove_time_interval")
        self.horizontalLayout.addWidget(self.dateEdit_DH_remove_time_interval)
        self.comboBox_DH_remove_time_interval = QtWidgets.QComboBox(self.frame_dh_operations)
        self.comboBox_DH_remove_time_interval.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_DH_remove_time_interval.setStyleSheet("QComboBox{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"\n"
"    border-width: 4px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: 14px;\n"
"\n"
"    padding: 6px;\n"
"}\n"
"QComboBox::hover{\n"
"    background-color: beige ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.comboBox_DH_remove_time_interval.setObjectName("comboBox_DH_remove_time_interval")
        self.comboBox_DH_remove_time_interval.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_DH_remove_time_interval)
        self.pushButton_DH_remove_time_interval = QtWidgets.QPushButton(self.frame_dh_operations)
        self.pushButton_DH_remove_time_interval.setMinimumSize(QtCore.QSize(192, 0))
        self.pushButton_DH_remove_time_interval.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(255, 144, 144);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color:rgb(255, 144, 144);\n"
"\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_DH_remove_time_interval.setObjectName("pushButton_DH_remove_time_interval")
        self.horizontalLayout.addWidget(self.pushButton_DH_remove_time_interval)
        self.gridLayout_8.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.pushButton_DH_clear_filter = QtWidgets.QPushButton(self.frame_dh_operations)
        self.pushButton_DH_clear_filter.setMinimumSize(QtCore.QSize(192, 0))
        self.pushButton_DH_clear_filter.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font:14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(206, 232, 255) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color:rgb(255, 144, 144);\n"
"\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_DH_clear_filter.setObjectName("pushButton_DH_clear_filter")
        self.gridLayout_8.addWidget(self.pushButton_DH_clear_filter, 1, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame_dh_operations, 3, 0, 1, 1)
        self.frame_daily_hours_input = QtWidgets.QFrame(self.Daily_Hours)
        self.frame_daily_hours_input.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_daily_hours_input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_daily_hours_input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_daily_hours_input.setObjectName("frame_daily_hours_input")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_daily_hours_input)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_DH_input = QtWidgets.QVBoxLayout()
        self.verticalLayout_DH_input.setObjectName("verticalLayout_DH_input")
        self.horizontalLayout_DH_input = QtWidgets.QHBoxLayout()
        self.horizontalLayout_DH_input.setObjectName("horizontalLayout_DH_input")
        self.verticalLayout_date = QtWidgets.QVBoxLayout()
        self.verticalLayout_date.setObjectName("verticalLayout_date")
        self.pushButton_DH_date = QtWidgets.QPushButton(self.frame_daily_hours_input)
        self.pushButton_DH_date.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(206, 232, 255) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color:rgb(255, 144, 144);\n"
"\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_DH_date.setObjectName("pushButton_DH_date")
        self.verticalLayout_date.addWidget(self.pushButton_DH_date)
        self.dateEdit_DH = QtWidgets.QDateEdit(self.frame_daily_hours_input)
        self.dateEdit_DH.setMinimumSize(QtCore.QSize(130, 0))
        self.dateEdit_DH.setStyleSheet("QDateEdit{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"    border-width: 4px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: 14px;\n"
"\n"
"    padding: 6px;\n"
"}\n"
"\n"
"\n"
"")
        self.dateEdit_DH.setCalendarPopup(False)
        self.dateEdit_DH.setObjectName("dateEdit_DH")
        self.verticalLayout_date.addWidget(self.dateEdit_DH)
        self.horizontalLayout_DH_input.addLayout(self.verticalLayout_date)
        self.verticalLayout_start = QtWidgets.QVBoxLayout()
        self.verticalLayout_start.setObjectName("verticalLayout_start")
        self.pushButton_DH_start = QtWidgets.QPushButton(self.frame_daily_hours_input)
        self.pushButton_DH_start.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_DH_start.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(206, 232, 255) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color:rgb(255, 144, 144);\n"
"\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_DH_start.setObjectName("pushButton_DH_start")
        self.verticalLayout_start.addWidget(self.pushButton_DH_start)
        self.timeEdit_DH_start = QtWidgets.QTimeEdit(self.frame_daily_hours_input)
        self.timeEdit_DH_start.setStyleSheet("QTimeEdit{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"\n"
"    border-width: 4px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: 14px;\n"
"\n"
"    padding: 6px;\n"
"}")
        self.timeEdit_DH_start.setCalendarPopup(False)
        self.timeEdit_DH_start.setObjectName("timeEdit_DH_start")
        self.verticalLayout_start.addWidget(self.timeEdit_DH_start)
        self.horizontalLayout_DH_input.addLayout(self.verticalLayout_start)
        self.verticalLayout_end = QtWidgets.QVBoxLayout()
        self.verticalLayout_end.setObjectName("verticalLayout_end")
        self.pushButton_DH_end = QtWidgets.QPushButton(self.frame_daily_hours_input)
        self.pushButton_DH_end.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_DH_end.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(206, 232, 255) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color:rgb(255, 144, 144);\n"
"\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_DH_end.setObjectName("pushButton_DH_end")
        self.verticalLayout_end.addWidget(self.pushButton_DH_end)
        self.timeEdit_DH_end = QtWidgets.QTimeEdit(self.frame_daily_hours_input)
        self.timeEdit_DH_end.setStyleSheet("QTimeEdit{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"\n"
"    border-width: 4px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: 14px;\n"
"\n"
"    padding: 6px;\n"
"}")
        self.timeEdit_DH_end.setObjectName("timeEdit_DH_end")
        self.verticalLayout_end.addWidget(self.timeEdit_DH_end)
        self.horizontalLayout_DH_input.addLayout(self.verticalLayout_end)
        self.verticalLayout_duration = QtWidgets.QVBoxLayout()
        self.verticalLayout_duration.setObjectName("verticalLayout_duration")
        self.label_DH_duration = QtWidgets.QLabel(self.frame_daily_hours_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_DH_duration.sizePolicy().hasHeightForWidth())
        self.label_DH_duration.setSizePolicy(sizePolicy)
        self.label_DH_duration.setMinimumSize(QtCore.QSize(0, 0))
        self.label_DH_duration.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_DH_duration.setStyleSheet("QLabel{\n"
"background-color: rgb(206, 232, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.label_DH_duration.setScaledContents(False)
        self.label_DH_duration.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DH_duration.setWordWrap(False)
        self.label_DH_duration.setObjectName("label_DH_duration")
        self.verticalLayout_duration.addWidget(self.label_DH_duration)
        self.label_DH_duration_time = QtWidgets.QLabel(self.frame_daily_hours_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_DH_duration_time.sizePolicy().hasHeightForWidth())
        self.label_DH_duration_time.setSizePolicy(sizePolicy)
        self.label_DH_duration_time.setMinimumSize(QtCore.QSize(0, 0))
        self.label_DH_duration_time.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_DH_duration_time.setStyleSheet("QLabel{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.label_DH_duration_time.setText("")
        self.label_DH_duration_time.setScaledContents(False)
        self.label_DH_duration_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DH_duration_time.setWordWrap(False)
        self.label_DH_duration_time.setObjectName("label_DH_duration_time")
        self.verticalLayout_duration.addWidget(self.label_DH_duration_time)
        self.horizontalLayout_DH_input.addLayout(self.verticalLayout_duration)
        self.verticalLayout_project_daily = QtWidgets.QVBoxLayout()
        self.verticalLayout_project_daily.setObjectName("verticalLayout_project_daily")
        self.label_DH_project = QtWidgets.QLabel(self.frame_daily_hours_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_DH_project.sizePolicy().hasHeightForWidth())
        self.label_DH_project.setSizePolicy(sizePolicy)
        self.label_DH_project.setMinimumSize(QtCore.QSize(0, 0))
        self.label_DH_project.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_DH_project.setStyleSheet("QLabel{\n"
"background-color: rgb(206, 232, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.label_DH_project.setScaledContents(False)
        self.label_DH_project.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DH_project.setWordWrap(False)
        self.label_DH_project.setObjectName("label_DH_project")
        self.verticalLayout_project_daily.addWidget(self.label_DH_project)
        self.comboBox_DH_project_add = QtWidgets.QComboBox(self.frame_daily_hours_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_DH_project_add.sizePolicy().hasHeightForWidth())
        self.comboBox_DH_project_add.setSizePolicy(sizePolicy)
        self.comboBox_DH_project_add.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_DH_project_add.setStyleSheet("QComboBox{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}\n"
"QComboBox::hover{\n"
"    background-color:rgb(206, 232, 255) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.comboBox_DH_project_add.setObjectName("comboBox_DH_project_add")
        self.verticalLayout_project_daily.addWidget(self.comboBox_DH_project_add)
        self.horizontalLayout_DH_input.addLayout(self.verticalLayout_project_daily)
        self.verticalLayout_add_info_daily = QtWidgets.QVBoxLayout()
        self.verticalLayout_add_info_daily.setObjectName("verticalLayout_add_info_daily")
        self.label_DH_add_info = QtWidgets.QLabel(self.frame_daily_hours_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_DH_add_info.sizePolicy().hasHeightForWidth())
        self.label_DH_add_info.setSizePolicy(sizePolicy)
        self.label_DH_add_info.setMinimumSize(QtCore.QSize(175, 0))
        self.label_DH_add_info.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_DH_add_info.setStyleSheet("QLabel{\n"
"background-color: rgb(206, 232, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.label_DH_add_info.setScaledContents(False)
        self.label_DH_add_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DH_add_info.setWordWrap(False)
        self.label_DH_add_info.setObjectName("label_DH_add_info")
        self.verticalLayout_add_info_daily.addWidget(self.label_DH_add_info)
        self.lineEdit_DH_add_info = QtWidgets.QLineEdit(self.frame_daily_hours_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_DH_add_info.sizePolicy().hasHeightForWidth())
        self.lineEdit_DH_add_info.setSizePolicy(sizePolicy)
        self.lineEdit_DH_add_info.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_DH_add_info.setStyleSheet("QLineEdit{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_DH_add_info.setObjectName("lineEdit_DH_add_info")
        self.verticalLayout_add_info_daily.addWidget(self.lineEdit_DH_add_info)
        self.horizontalLayout_DH_input.addLayout(self.verticalLayout_add_info_daily)
        self.verticalLayout_DH_input.addLayout(self.horizontalLayout_DH_input)
        self.pushButton_DH_add_to_table = QtWidgets.QPushButton(self.frame_daily_hours_input)
        self.pushButton_DH_add_to_table.setMinimumSize(QtCore.QSize(192, 0))
        self.pushButton_DH_add_to_table.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color:rgb(206, 232, 255) ;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color:rgb(255, 144, 144);\n"
"\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_DH_add_to_table.setObjectName("pushButton_DH_add_to_table")
        self.verticalLayout_DH_input.addWidget(self.pushButton_DH_add_to_table)
        self.gridLayout_10.addLayout(self.verticalLayout_DH_input, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame_daily_hours_input, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Daily_Hours, "")
        self.Weekly_Hours = QtWidgets.QWidget()
        self.Weekly_Hours.setObjectName("Weekly_Hours")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Weekly_Hours)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.frame_hours_input = QtWidgets.QFrame(self.Weekly_Hours)
        self.frame_hours_input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_hours_input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_hours_input.setObjectName("frame_hours_input")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_hours_input)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_hours_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label.setStyleSheet("QLabel{\n"
"background-color: rgb(206, 232, 255);\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    padding: 2px;\n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_WH_P_ID = QtWidgets.QLabel(self.frame_hours_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_WH_P_ID.sizePolicy().hasHeightForWidth())
        self.label_WH_P_ID.setSizePolicy(sizePolicy)
        self.label_WH_P_ID.setMinimumSize(QtCore.QSize(0, 35))
        self.label_WH_P_ID.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_WH_P_ID.setStyleSheet("QLabel{\n"
"background-color: rgb(206, 232, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.label_WH_P_ID.setScaledContents(False)
        self.label_WH_P_ID.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WH_P_ID.setWordWrap(False)
        self.label_WH_P_ID.setObjectName("label_WH_P_ID")
        self.horizontalLayout_3.addWidget(self.label_WH_P_ID)
        self.label_WH_p_t_num = QtWidgets.QLabel(self.frame_hours_input)
        self.label_WH_p_t_num.setStyleSheet("QLabel{\n"
"background-color: rgb(206, 232, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.label_WH_p_t_num.setObjectName("label_WH_p_t_num")
        self.horizontalLayout_3.addWidget(self.label_WH_p_t_num)
        self.label_WH_monday_date = QtWidgets.QLabel(self.frame_hours_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_WH_monday_date.sizePolicy().hasHeightForWidth())
        self.label_WH_monday_date.setSizePolicy(sizePolicy)
        self.label_WH_monday_date.setMinimumSize(QtCore.QSize(0, 35))
        self.label_WH_monday_date.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_WH_monday_date.setStyleSheet("QLabel{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font:14px;\n"
"    padding: 6px;\n"
"}")
        self.label_WH_monday_date.setText("")
        self.label_WH_monday_date.setScaledContents(False)
        self.label_WH_monday_date.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WH_monday_date.setWordWrap(False)
        self.label_WH_monday_date.setObjectName("label_WH_monday_date")
        self.horizontalLayout_3.addWidget(self.label_WH_monday_date)
        self.label_WH_tuesday_date = QtWidgets.QLabel(self.frame_hours_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_WH_tuesday_date.sizePolicy().hasHeightForWidth())
        self.label_WH_tuesday_date.setSizePolicy(sizePolicy)
        self.label_WH_tuesday_date.setMinimumSize(QtCore.QSize(0, 35))
        self.label_WH_tuesday_date.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_WH_tuesday_date.setStyleSheet("QLabel{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font:14px;\n"
"    padding: 6px;\n"
"}")
        self.label_WH_tuesday_date.setText("")
        self.label_WH_tuesday_date.setScaledContents(False)
        self.label_WH_tuesday_date.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WH_tuesday_date.setWordWrap(False)
        self.label_WH_tuesday_date.setObjectName("label_WH_tuesday_date")
        self.horizontalLayout_3.addWidget(self.label_WH_tuesday_date)
        self.label_WH_wednesday_date = QtWidgets.QLabel(self.frame_hours_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_WH_wednesday_date.sizePolicy().hasHeightForWidth())
        self.label_WH_wednesday_date.setSizePolicy(sizePolicy)
        self.label_WH_wednesday_date.setMinimumSize(QtCore.QSize(0, 35))
        self.label_WH_wednesday_date.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_WH_wednesday_date.setStyleSheet("QLabel{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font:14px;\n"
"    padding: 6px;\n"
"}")
        self.label_WH_wednesday_date.setText("")
        self.label_WH_wednesday_date.setScaledContents(False)
        self.label_WH_wednesday_date.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WH_wednesday_date.setWordWrap(False)
        self.label_WH_wednesday_date.setObjectName("label_WH_wednesday_date")
        self.horizontalLayout_3.addWidget(self.label_WH_wednesday_date)
        self.label_WH_thursday_date = QtWidgets.QLabel(self.frame_hours_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_WH_thursday_date.sizePolicy().hasHeightForWidth())
        self.label_WH_thursday_date.setSizePolicy(sizePolicy)
        self.label_WH_thursday_date.setMinimumSize(QtCore.QSize(0, 35))
        self.label_WH_thursday_date.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_WH_thursday_date.setStyleSheet("QLabel{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font:14px;\n"
"    padding: 6px;\n"
"}")
        self.label_WH_thursday_date.setText("")
        self.label_WH_thursday_date.setScaledContents(False)
        self.label_WH_thursday_date.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WH_thursday_date.setWordWrap(False)
        self.label_WH_thursday_date.setObjectName("label_WH_thursday_date")
        self.horizontalLayout_3.addWidget(self.label_WH_thursday_date)
        self.label_WH_friday_date = QtWidgets.QLabel(self.frame_hours_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_WH_friday_date.sizePolicy().hasHeightForWidth())
        self.label_WH_friday_date.setSizePolicy(sizePolicy)
        self.label_WH_friday_date.setMinimumSize(QtCore.QSize(0, 35))
        self.label_WH_friday_date.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_WH_friday_date.setStyleSheet("QLabel{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font:14px;\n"
"    padding: 6px;\n"
"}")
        self.label_WH_friday_date.setText("")
        self.label_WH_friday_date.setScaledContents(False)
        self.label_WH_friday_date.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WH_friday_date.setWordWrap(False)
        self.label_WH_friday_date.setObjectName("label_WH_friday_date")
        self.horizontalLayout_3.addWidget(self.label_WH_friday_date)
        self.label_2 = QtWidgets.QLabel(self.frame_hours_input)
        self.label_2.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tableView_WH_project = QtWidgets.QTableView(self.frame_hours_input)
        self.tableView_WH_project.setStyleSheet("QTableView{\n"
"background-color:white;    \n"
"border-style:outset;\n"
"\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: 13px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.tableView_WH_project.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableView_WH_project.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableView_WH_project.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView_WH_project.setAlternatingRowColors(True)
        self.tableView_WH_project.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableView_WH_project.setSortingEnabled(True)
        self.tableView_WH_project.setObjectName("tableView_WH_project")
        self.verticalLayout.addWidget(self.tableView_WH_project)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_WH_place1 = QtWidgets.QLabel(self.frame_hours_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_WH_place1.sizePolicy().hasHeightForWidth())
        self.label_WH_place1.setSizePolicy(sizePolicy)
        self.label_WH_place1.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_WH_place1.setStyleSheet("")
        self.label_WH_place1.setText("")
        self.label_WH_place1.setObjectName("label_WH_place1")
        self.horizontalLayout_4.addWidget(self.label_WH_place1)
        self.label_WH_total_hours = QtWidgets.QLabel(self.frame_hours_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_WH_total_hours.sizePolicy().hasHeightForWidth())
        self.label_WH_total_hours.setSizePolicy(sizePolicy)
        self.label_WH_total_hours.setMinimumSize(QtCore.QSize(0, 35))
        self.label_WH_total_hours.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_WH_total_hours.setStyleSheet("QLabel{\n"
"background-color: rgb(206, 232, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.label_WH_total_hours.setScaledContents(False)
        self.label_WH_total_hours.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WH_total_hours.setWordWrap(False)
        self.label_WH_total_hours.setObjectName("label_WH_total_hours")
        self.horizontalLayout_4.addWidget(self.label_WH_total_hours)
        self.label_WH_sum_total = QtWidgets.QLabel(self.frame_hours_input)
        self.label_WH_sum_total.setStyleSheet("QLabel{\n"
"background-color: rgb(206, 232, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.label_WH_sum_total.setText("")
        self.label_WH_sum_total.setObjectName("label_WH_sum_total")
        self.horizontalLayout_4.addWidget(self.label_WH_sum_total)
        self.label_WH_sum_monday = QtWidgets.QLabel(self.frame_hours_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_WH_sum_monday.sizePolicy().hasHeightForWidth())
        self.label_WH_sum_monday.setSizePolicy(sizePolicy)
        self.label_WH_sum_monday.setMinimumSize(QtCore.QSize(0, 35))
        self.label_WH_sum_monday.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_WH_sum_monday.setStyleSheet("QLabel{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font:14px;\n"
"    padding: 6px;\n"
"}")
        self.label_WH_sum_monday.setText("")
        self.label_WH_sum_monday.setScaledContents(False)
        self.label_WH_sum_monday.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WH_sum_monday.setWordWrap(False)
        self.label_WH_sum_monday.setObjectName("label_WH_sum_monday")
        self.horizontalLayout_4.addWidget(self.label_WH_sum_monday)
        self.label_WH_sum_tuesday = QtWidgets.QLabel(self.frame_hours_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_WH_sum_tuesday.sizePolicy().hasHeightForWidth())
        self.label_WH_sum_tuesday.setSizePolicy(sizePolicy)
        self.label_WH_sum_tuesday.setMinimumSize(QtCore.QSize(0, 35))
        self.label_WH_sum_tuesday.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_WH_sum_tuesday.setStyleSheet("QLabel{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font:14px;\n"
"    padding: 6px;\n"
"}")
        self.label_WH_sum_tuesday.setText("")
        self.label_WH_sum_tuesday.setScaledContents(False)
        self.label_WH_sum_tuesday.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WH_sum_tuesday.setWordWrap(False)
        self.label_WH_sum_tuesday.setObjectName("label_WH_sum_tuesday")
        self.horizontalLayout_4.addWidget(self.label_WH_sum_tuesday)
        self.label_WH_sum_wednesday = QtWidgets.QLabel(self.frame_hours_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_WH_sum_wednesday.sizePolicy().hasHeightForWidth())
        self.label_WH_sum_wednesday.setSizePolicy(sizePolicy)
        self.label_WH_sum_wednesday.setMinimumSize(QtCore.QSize(0, 35))
        self.label_WH_sum_wednesday.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_WH_sum_wednesday.setStyleSheet("QLabel{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font:14px;\n"
"    padding: 6px;\n"
"}")
        self.label_WH_sum_wednesday.setText("")
        self.label_WH_sum_wednesday.setScaledContents(False)
        self.label_WH_sum_wednesday.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WH_sum_wednesday.setWordWrap(False)
        self.label_WH_sum_wednesday.setObjectName("label_WH_sum_wednesday")
        self.horizontalLayout_4.addWidget(self.label_WH_sum_wednesday)
        self.label_WH_sum_thursday = QtWidgets.QLabel(self.frame_hours_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_WH_sum_thursday.sizePolicy().hasHeightForWidth())
        self.label_WH_sum_thursday.setSizePolicy(sizePolicy)
        self.label_WH_sum_thursday.setMinimumSize(QtCore.QSize(0, 35))
        self.label_WH_sum_thursday.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_WH_sum_thursday.setStyleSheet("QLabel{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font:14px;\n"
"    padding: 6px;\n"
"}")
        self.label_WH_sum_thursday.setText("")
        self.label_WH_sum_thursday.setScaledContents(False)
        self.label_WH_sum_thursday.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WH_sum_thursday.setWordWrap(False)
        self.label_WH_sum_thursday.setObjectName("label_WH_sum_thursday")
        self.horizontalLayout_4.addWidget(self.label_WH_sum_thursday)
        self.label_WH_sum_friday = QtWidgets.QLabel(self.frame_hours_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_WH_sum_friday.sizePolicy().hasHeightForWidth())
        self.label_WH_sum_friday.setSizePolicy(sizePolicy)
        self.label_WH_sum_friday.setMinimumSize(QtCore.QSize(0, 35))
        self.label_WH_sum_friday.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_WH_sum_friday.setStyleSheet("QLabel{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font:14px;\n"
"    padding: 6px;\n"
"}")
        self.label_WH_sum_friday.setText("")
        self.label_WH_sum_friday.setScaledContents(False)
        self.label_WH_sum_friday.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WH_sum_friday.setWordWrap(False)
        self.label_WH_sum_friday.setObjectName("label_WH_sum_friday")
        self.horizontalLayout_4.addWidget(self.label_WH_sum_friday)
        self.label_WH_place2 = QtWidgets.QLabel(self.frame_hours_input)
        self.label_WH_place2.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_WH_place2.setText("")
        self.label_WH_place2.setObjectName("label_WH_place2")
        self.horizontalLayout_4.addWidget(self.label_WH_place2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout_14.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_hours_input, 1, 0, 1, 1)
        self.frame_week_project_select = QtWidgets.QFrame(self.Weekly_Hours)
        self.frame_week_project_select.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_week_project_select.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_week_project_select.setObjectName("frame_week_project_select")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_week_project_select)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.calendarWidget_WH = QtWidgets.QCalendarWidget(self.frame_week_project_select)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget_WH.sizePolicy().hasHeightForWidth())
        self.calendarWidget_WH.setSizePolicy(sizePolicy)
        self.calendarWidget_WH.setStyleSheet("background-color: rgb(228, 228, 228);")
        self.calendarWidget_WH.setObjectName("calendarWidget_WH")
        self.gridLayout_3.addWidget(self.calendarWidget_WH, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.spinBox_WH_year = QtWidgets.QSpinBox(self.frame_week_project_select)
        self.spinBox_WH_year.setStyleSheet("QSpinBox{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.spinBox_WH_year.setMinimum(2000)
        self.spinBox_WH_year.setMaximum(2050)
        self.spinBox_WH_year.setProperty("value", 2023)
        self.spinBox_WH_year.setObjectName("spinBox_WH_year")
        self.horizontalLayout_2.addWidget(self.spinBox_WH_year)
        self.pushButton_WH_week = QtWidgets.QPushButton(self.frame_week_project_select)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_WH_week.sizePolicy().hasHeightForWidth())
        self.pushButton_WH_week.setSizePolicy(sizePolicy)
        self.pushButton_WH_week.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_WH_week.setStyleSheet("QPushButton{\n"
"    background-color: rgb(220, 247, 255);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-radius: 10px;\n"
"   border-color: rgb(255, 200, 200);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(206, 232, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 144, 144);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_WH_week.setObjectName("pushButton_WH_week")
        self.horizontalLayout_2.addWidget(self.pushButton_WH_week)
        self.spinBox_WH_week = QtWidgets.QSpinBox(self.frame_week_project_select)
        self.spinBox_WH_week.setStyleSheet("QSpinBox{\n"
"background-color:beige;    \n"
"border-style:outset;\n"
"\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"border-color: rgb(220, 247, 255);\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}")
        self.spinBox_WH_week.setMinimum(1)
        self.spinBox_WH_week.setMaximum(52)
        self.spinBox_WH_week.setObjectName("spinBox_WH_week")
        self.horizontalLayout_2.addWidget(self.spinBox_WH_week)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_week_project_select, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Weekly_Hours, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(180, 170, 431, 321))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(60, 60, 69, 22))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.horizontalSlider = QtWidgets.QSlider(self.tab)
        self.horizontalSlider.setGeometry(QtCore.QRect(190, 60, 160, 22))
        self.horizontalSlider.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.tableView = QtWidgets.QTableView(self.tab)
        self.tableView.setGeometry(QtCore.QRect(240, 530, 256, 192))
        self.tableView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableView.setObjectName("tableView")
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_12.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 892, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDelete_All_projects = QtWidgets.QAction(MainWindow)
        self.actionDelete_All_projects.setObjectName("actionDelete_All_projects")
        self.actionDelete_All_Daily_Hours = QtWidgets.QAction(MainWindow)
        self.actionDelete_All_Daily_Hours.setObjectName("actionDelete_All_Daily_Hours")
        self.menuEdit.addAction(self.actionDelete_All_projects)
        self.menuEdit.addAction(self.actionDelete_All_Daily_Hours)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.pushButton_PI_add_project.clicked.connect(MainWindow.PI_add_project)
        self.pushButton_PI_clear_input.clicked.connect(MainWindow.PI_clear_input)
        self.pushButton_PI_delete_project.clicked.connect(MainWindow.PI_delete_project)
        self.pushButton_DH_sum_up.clicked.connect(MainWindow.DH_sum_date)
        self.pushButton_DH_remove_time_interval.clicked.connect(MainWindow.DH_remove_time_interval)
        self.actionDelete_All_projects.triggered.connect(MainWindow.delete_all_projects)
        self.actionDelete_All_Daily_Hours.triggered.connect(MainWindow.delete_all_daily_hours)
        self.pushButton_WH_week.clicked.connect(MainWindow.WH_this_week)
        self.pushButton_DH_start.clicked.connect(MainWindow.DH_start_now)
        self.pushButton_DH_end.clicked.connect(MainWindow.DH_end_now)
        self.pushButton_DH_add_to_table.clicked.connect(MainWindow.DH_add_to_table)
        self.pushButton_DH_date.clicked.connect(MainWindow.DH_date_now)
        self.lineEdit_PI_search_table.textChanged['QString'].connect(MainWindow.PI_search_table_changed)
        self.lineEdit_DH_search_table.textChanged['QString'].connect(MainWindow.DH_search_table_changed)
        self.dateEdit_DH_remove_time_interval.dateChanged['QDate'].connect(MainWindow.DH_apply_date_filter)
        self.pushButton_DH_clear_filter.clicked.connect(MainWindow.DH_clear_filter)
        self.spinBox_WH_week.valueChanged['int'].connect(MainWindow.WH_week_changed)
        self.calendarWidget_WH.selectionChanged.connect(MainWindow.WH_calander_changed)
        self.spinBox_WH_year.valueChanged['int'].connect(MainWindow.WH_week_changed)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_PI_client.setText(_translate("MainWindow", "Client"))
        self.label_PI_p_name.setText(_translate("MainWindow", "Project Name"))
        self.label_PI_p_number.setText(_translate("MainWindow", "Project Number"))
        self.label_PI_t_number.setText(_translate("MainWindow", "Task Number"))
        self.label_PI_rate.setText(_translate("MainWindow", "Hourly Rate"))
        self.comboBox_PI_currency.setItemText(0, _translate("MainWindow", "€ Euro"))
        self.comboBox_PI_currency.setItemText(1, _translate("MainWindow", "$ Dollar"))
        self.label_PI_add_info.setText(_translate("MainWindow", "Additional Information"))
        self.pushButton_PI_clear_input.setText(_translate("MainWindow", "Clear \n"
" Input"))
        self.pushButton_PI_add_project.setText(_translate("MainWindow", "ADD project"))
        self.lineEdit_PI_search_table.setPlaceholderText(_translate("MainWindow", "Search ..."))
        self.comboBox_PI_project_del.setItemText(0, _translate("MainWindow", "Select Project"))
        self.pushButton_PI_delete_project.setText(_translate("MainWindow", "Delete project"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Project_Input), _translate("MainWindow", "Project Input"))
        self.lineEdit_DH_search_table.setPlaceholderText(_translate("MainWindow", "Search ...."))
        self.pushButton_DH_sum_up.setText(_translate("MainWindow", "Sum up Daily Hours"))
        self.comboBox_DH_remove_time_interval.setItemText(0, _translate("MainWindow", "Project filter"))
        self.pushButton_DH_remove_time_interval.setText(_translate("MainWindow", "Remove Time Inteval"))
        self.pushButton_DH_clear_filter.setText(_translate("MainWindow", "Clear Filter"))
        self.pushButton_DH_date.setText(_translate("MainWindow", "Date"))
        self.pushButton_DH_start.setText(_translate("MainWindow", "Start "))
        self.pushButton_DH_end.setText(_translate("MainWindow", "End"))
        self.label_DH_duration.setText(_translate("MainWindow", "Duration"))
        self.label_DH_project.setText(_translate("MainWindow", "Project"))
        self.label_DH_add_info.setText(_translate("MainWindow", "Additional information"))
        self.pushButton_DH_add_to_table.setText(_translate("MainWindow", "Add to Table"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Daily_Hours), _translate("MainWindow", "Daily Hours"))
        self.label.setText(_translate("MainWindow", "#"))
        self.label_WH_P_ID.setText(_translate("MainWindow", "Project ID"))
        self.label_WH_p_t_num.setText(_translate("MainWindow", "Proj-Task#"))
        self.label_WH_total_hours.setText(_translate("MainWindow", "Total:"))
        self.pushButton_WH_week.setText(_translate("MainWindow", "Week"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Weekly_Hours), _translate("MainWindow", "Weekly Hours"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Plots"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionDelete_All_projects.setText(_translate("MainWindow", "Delete All projects"))
        self.actionDelete_All_Daily_Hours.setText(_translate("MainWindow", "Delete All Daily Hours"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
